In [87]:
# Jupyter notebook
import pandas as pd
import pandasql as psql
import glob

In [88]:
clinical_codes = pd.read_csv(r'../exa-data-analyst-assessment/data/clinical_codes.csv')
patient = pd.read_csv(r'../exa-data-analyst-assessment/data/patient.csv')

In [89]:
# Creates a varaible name for each medication file in folder [medication1, medication2, ... ,medicationx]

# Note that variables 0 to 14 are now mapped to filenames 1, 10, 11, 12, 13, 14, 15, 2, 3, 4, 5, 6, 7, 8, 9 respectively

medication_list = glob.glob(r'../exa-data-analyst-assessment/data/medication/*.csv')
for n, val in enumerate(medication_list):
    globals()["medication%d"%n] = pd.read_csv(val, header=None)

# Creates a variable name for each observation file in folder [observation1, observation2, ..., observationx]

# Note that variables 0 to 11 are now mapped to filenames 1, 10, 11, 12, 2, 3, 4, 5, 6, 7, 8, 9 respectively

observation_list = glob.glob(r'../exa-data-analyst-assessment/data/observation/*.csv')
for n, val in enumerate(observation_list):
    globals()["observation%d"%n] = pd.read_csv(val, header=None)
observation0

C:\Users\User\AppData\Local\Temp\ipykernel_17036\3519892758.py:15: DtypeWarning: Columns (0,1,2,3,4,5,8,12,19,20,22,23,24,25,26,30,31,35,36,37,39,40,41,42,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  globals()["observation%d"%n] = pd.read_csv(val, header=None)
C:\Users\User\AppData\Local\Temp\ipykernel_17036\3519892758.py:15: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  globals()["observation%d"%n] = pd.read_csv(val, header=None)
C:\Users\User\AppData\Local\Temp\ipykernel_17036\3519892758.py:15: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  globals()["observation%d"%n] = pd.read_csv(val, header=None)
C:\Users\User\AppData\Local\Temp\ipykernel_17036\3519892758.py:15: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  globals()["observation%d"%n] = pd.read_csv(val, header=None)
C:\Users\User\AppData\Local\Temp\ipykernel_17036\3519892758.py:15: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  globals()["observation%d"%n] = pd.read_csv(val, header=None)

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,abnormal,emis_code_id,comparator,confidential_flag,confidential_patient_flag,consultation_source_emis_code_id,consultation_source_emis_original_term,document_guid,dummy_patient_flag,effective_date,...,sensitive_patient_flag,snomed_concept_id,snomed_description_id,emis_parent_observation_guid,exa_parent_observation_guid,uom,uom_ucum,user_selected,numericvalue,value_pq_2
1,false,254063019,NaN,false,false,1672871000006114,Main Surgery,NaN,false,1999-08-12 00:00:00,...,false,163020007,254063019,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,false,259803019,NaN,false,false,1672871000006114,Main Surgery,NaN,false,2000-01-13 00:00:00,...,false,167273002,259803019,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,false,215711000006110,NaN,false,false,1672871000006114,Main Surgery,NaN,false,2000-02-03 00:00:00,...,false,286647002,426047013,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,false,253669010,NaN,false,false,1672871000006114,Main Surgery,NaN,false,2003-11-21 00:00:00,...,false,248333004,370729019,NaN,NaN,cm,cm,NaN,150.000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23182,False,1208954011,NaN,False,False,1672871000006114.0,Main Surgery,NaN,False,2001-03-23 00:00:00,...,False,370202007,1208954011,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23183,False,254063019,NaN,False,False,1672871000006114.0,Main Surgery,NaN,False,2003-12-03 00:00:00,...,False,163020007,254063019,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23184,False,264567012,NaN,False,False,1672871000006114.0,Main Surgery,NaN,False,2000-10-08 00:00:00,...,False,170656008,264567012,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23185,True,1495289019,NaN,False,False,1672871000006114.0,General Practice Surgery,NaN,False,2004-02-29 00:00:00,...,False,997531000000108,2572661000000117,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23186,False,259579011,NaN,False,False,NaN,NaN,NaN,False,2005-04-06 00:00:00,...,False,1010601000000105,2564971000000119,265A7273-2863-4AAF-BDF7-881DD528BAB2,2455013f-7c79-5b3d-90f9-03fec5de7d9c,mmol/L,mmol/L,NaN,1.1,NaN

In [90]:
# Concatenating all observation csvs into one table

observation0 = observation0.iloc[1:] # column names are first row
observation0
observation0 = observation0.set_axis(["abnormal","emis_code_id","comparator","confidential_flag","confidential_patient_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","document_guid","dummy_patient_flag","effective_date","effective_date_precision","emis_enteredby_userinrole_guid","emis_episodicity","end_date","fhir_episodicity","emis_observation_guid","exa_observation_guid","fhir_interpretation_code","is_parent_flag","non_regular_and_current_active_flag","emis_observation_id","observation_type","emis_observationtypeid","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","other_code","other_code_system","other_display","range_lower","range_upper","readv2_code","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","emis_parent_observation_guid","exa_parent_observation_guid","uom","uom_ucum","user_selected","numericvalue","value_pq_2"], axis = 1)
observation1 = observation1.set_axis(["abnormal","emis_code_id","comparator","confidential_flag","confidential_patient_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","document_guid","dummy_patient_flag","effective_date","effective_date_precision","emis_enteredby_userinrole_guid","emis_episodicity","end_date","fhir_episodicity","emis_observation_guid","exa_observation_guid","fhir_interpretation_code","is_parent_flag","non_regular_and_current_active_flag","emis_observation_id","observation_type","emis_observationtypeid","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","other_code","other_code_system","other_display","range_lower","range_upper","readv2_code","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","emis_parent_observation_guid","exa_parent_observation_guid","uom","uom_ucum","user_selected","numericvalue","value_pq_2"], axis = 1)
observation2 = observation2.set_axis(["abnormal","emis_code_id","comparator","confidential_flag","confidential_patient_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","document_guid","dummy_patient_flag","effective_date","effective_date_precision","emis_enteredby_userinrole_guid","emis_episodicity","end_date","fhir_episodicity","emis_observation_guid","exa_observation_guid","fhir_interpretation_code","is_parent_flag","non_regular_and_current_active_flag","emis_observation_id","observation_type","emis_observationtypeid","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","other_code","other_code_system","other_display","range_lower","range_upper","readv2_code","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","emis_parent_observation_guid","exa_parent_observation_guid","uom","uom_ucum","user_selected","numericvalue","value_pq_2"], axis = 1)
observation3 = observation3.set_axis(["abnormal","emis_code_id","comparator","confidential_flag","confidential_patient_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","document_guid","dummy_patient_flag","effective_date","effective_date_precision","emis_enteredby_userinrole_guid","emis_episodicity","end_date","fhir_episodicity","emis_observation_guid","exa_observation_guid","fhir_interpretation_code","is_parent_flag","non_regular_and_current_active_flag","emis_observation_id","observation_type","emis_observationtypeid","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","other_code","other_code_system","other_display","range_lower","range_upper","readv2_code","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","emis_parent_observation_guid","exa_parent_observation_guid","uom","uom_ucum","user_selected","numericvalue","value_pq_2"], axis = 1)
observation4 = observation4.set_axis(["abnormal","emis_code_id","comparator","confidential_flag","confidential_patient_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","document_guid","dummy_patient_flag","effective_date","effective_date_precision","emis_enteredby_userinrole_guid","emis_episodicity","end_date","fhir_episodicity","emis_observation_guid","exa_observation_guid","fhir_interpretation_code","is_parent_flag","non_regular_and_current_active_flag","emis_observation_id","observation_type","emis_observationtypeid","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","other_code","other_code_system","other_display","range_lower","range_upper","readv2_code","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","emis_parent_observation_guid","exa_parent_observation_guid","uom","uom_ucum","user_selected","numericvalue","value_pq_2"], axis = 1)
observation5 = observation5.set_axis(["abnormal","emis_code_id","comparator","confidential_flag","confidential_patient_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","document_guid","dummy_patient_flag","effective_date","effective_date_precision","emis_enteredby_userinrole_guid","emis_episodicity","end_date","fhir_episodicity","emis_observation_guid","exa_observation_guid","fhir_interpretation_code","is_parent_flag","non_regular_and_current_active_flag","emis_observation_id","observation_type","emis_observationtypeid","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","other_code","other_code_system","other_display","range_lower","range_upper","readv2_code","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","emis_parent_observation_guid","exa_parent_observation_guid","uom","uom_ucum","user_selected","numericvalue","value_pq_2"], axis = 1)
observation6 = observation6.set_axis(["abnormal","emis_code_id","comparator","confidential_flag","confidential_patient_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","document_guid","dummy_patient_flag","effective_date","effective_date_precision","emis_enteredby_userinrole_guid","emis_episodicity","end_date","fhir_episodicity","emis_observation_guid","exa_observation_guid","fhir_interpretation_code","is_parent_flag","non_regular_and_current_active_flag","emis_observation_id","observation_type","emis_observationtypeid","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","other_code","other_code_system","other_display","range_lower","range_upper","readv2_code","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","emis_parent_observation_guid","exa_parent_observation_guid","uom","uom_ucum","user_selected","numericvalue","value_pq_2"], axis = 1)
observation7 = observation7.set_axis(["abnormal","emis_code_id","comparator","confidential_flag","confidential_patient_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","document_guid","dummy_patient_flag","effective_date","effective_date_precision","emis_enteredby_userinrole_guid","emis_episodicity","end_date","fhir_episodicity","emis_observation_guid","exa_observation_guid","fhir_interpretation_code","is_parent_flag","non_regular_and_current_active_flag","emis_observation_id","observation_type","emis_observationtypeid","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","other_code","other_code_system","other_display","range_lower","range_upper","readv2_code","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","emis_parent_observation_guid","exa_parent_observation_guid","uom","uom_ucum","user_selected","numericvalue","value_pq_2"], axis = 1)
observation8 = observation8.set_axis(["abnormal","emis_code_id","comparator","confidential_flag","confidential_patient_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","document_guid","dummy_patient_flag","effective_date","effective_date_precision","emis_enteredby_userinrole_guid","emis_episodicity","end_date","fhir_episodicity","emis_observation_guid","exa_observation_guid","fhir_interpretation_code","is_parent_flag","non_regular_and_current_active_flag","emis_observation_id","observation_type","emis_observationtypeid","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","other_code","other_code_system","other_display","range_lower","range_upper","readv2_code","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","emis_parent_observation_guid","exa_parent_observation_guid","uom","uom_ucum","user_selected","numericvalue","value_pq_2"], axis = 1)
observation9 = observation9.set_axis(["abnormal","emis_code_id","comparator","confidential_flag","confidential_patient_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","document_guid","dummy_patient_flag","effective_date","effective_date_precision","emis_enteredby_userinrole_guid","emis_episodicity","end_date","fhir_episodicity","emis_observation_guid","exa_observation_guid","fhir_interpretation_code","is_parent_flag","non_regular_and_current_active_flag","emis_observation_id","observation_type","emis_observationtypeid","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","other_code","other_code_system","other_display","range_lower","range_upper","readv2_code","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","emis_parent_observation_guid","exa_parent_observation_guid","uom","uom_ucum","user_selected","numericvalue","value_pq_2"], axis = 1)
observation10 = observation10.set_axis(["abnormal","emis_code_id","comparator","confidential_flag","confidential_patient_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","document_guid","dummy_patient_flag","effective_date","effective_date_precision","emis_enteredby_userinrole_guid","emis_episodicity","end_date","fhir_episodicity","emis_observation_guid","exa_observation_guid","fhir_interpretation_code","is_parent_flag","non_regular_and_current_active_flag","emis_observation_id","observation_type","emis_observationtypeid","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","other_code","other_code_system","other_display","range_lower","range_upper","readv2_code","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","emis_parent_observation_guid","exa_parent_observation_guid","uom","uom_ucum","user_selected","numericvalue","value_pq_2"], axis = 1)
observation11 = observation11.set_axis(["abnormal","emis_code_id","comparator","confidential_flag","confidential_patient_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","document_guid","dummy_patient_flag","effective_date","effective_date_precision","emis_enteredby_userinrole_guid","emis_episodicity","end_date","fhir_episodicity","emis_observation_guid","exa_observation_guid","fhir_interpretation_code","is_parent_flag","non_regular_and_current_active_flag","emis_observation_id","observation_type","emis_observationtypeid","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","other_code","other_code_system","other_display","range_lower","range_upper","readv2_code","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","emis_parent_observation_guid","exa_parent_observation_guid","uom","uom_ucum","user_selected","numericvalue","value_pq_2"], axis = 1)

observation_list = [observation0, observation1, observation2, observation3, observation4, observation5, observation6, observation7, observation8, observation9, observation10, observation11]

observation_table = pd.concat(observation_list)

# observation_table

In [91]:
# Concatenating all medication csvs into one table

medication0 = medication0.iloc[1:] # column names are first row
# medication0
medication0 = medication0.set_axis(["nhs_prescribing_agency","emis_drug_guid","authorisedissues_authorised_date","authorisedissues_first_issue_date","cancellation_reason","emis_code_id","confidential_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","dose","emis_medication_status","dummy_patient_flag","duration_in_days","duration_uom","effective_date","effective_date_precision","emis_issue_method","emis_mostrecent_issue_date","emis_prescription_type","emis_registration_organisation_guid","emis_encounter_guid","exa_encounter_guid","end_date","emis_enteredby_userinrole_guid","exa_prescription_guid","estimated_nhs_cost","exa_drug_guid","medication_guid","exa_medication_guid","fhir_medication_intent","exa_mostrecent_issue_date","max_nextissue_days","min_nextissue_days","non_regular_and_current_active_flag","number_authorised","number_of_issues","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","emis_medication_organisation_guid","other_code","other_code_system","prescribed_as_contraceptive_flag","privately_prescribed_flag","quantity","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","reimburse_type","review_date","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","fhir_medication_status","cancellation_date","nhs_prescription_type","uom","uom_dmd"], axis = 1)
medication1 = medication1.set_axis(["nhs_prescribing_agency","emis_drug_guid","authorisedissues_authorised_date","authorisedissues_first_issue_date","cancellation_reason","emis_code_id","confidential_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","dose","emis_medication_status","dummy_patient_flag","duration_in_days","duration_uom","effective_date","effective_date_precision","emis_issue_method","emis_mostrecent_issue_date","emis_prescription_type","emis_registration_organisation_guid","emis_encounter_guid","exa_encounter_guid","end_date","emis_enteredby_userinrole_guid","exa_prescription_guid","estimated_nhs_cost","exa_drug_guid","medication_guid","exa_medication_guid","fhir_medication_intent","exa_mostrecent_issue_date","max_nextissue_days","min_nextissue_days","non_regular_and_current_active_flag","number_authorised","number_of_issues","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","emis_medication_organisation_guid","other_code","other_code_system","prescribed_as_contraceptive_flag","privately_prescribed_flag","quantity","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","reimburse_type","review_date","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","fhir_medication_status","cancellation_date","nhs_prescription_type","uom","uom_dmd"], axis = 1)
medication2 = medication2.set_axis(["nhs_prescribing_agency","emis_drug_guid","authorisedissues_authorised_date","authorisedissues_first_issue_date","cancellation_reason","emis_code_id","confidential_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","dose","emis_medication_status","dummy_patient_flag","duration_in_days","duration_uom","effective_date","effective_date_precision","emis_issue_method","emis_mostrecent_issue_date","emis_prescription_type","emis_registration_organisation_guid","emis_encounter_guid","exa_encounter_guid","end_date","emis_enteredby_userinrole_guid","exa_prescription_guid","estimated_nhs_cost","exa_drug_guid","medication_guid","exa_medication_guid","fhir_medication_intent","exa_mostrecent_issue_date","max_nextissue_days","min_nextissue_days","non_regular_and_current_active_flag","number_authorised","number_of_issues","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","emis_medication_organisation_guid","other_code","other_code_system","prescribed_as_contraceptive_flag","privately_prescribed_flag","quantity","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","reimburse_type","review_date","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","fhir_medication_status","cancellation_date","nhs_prescription_type","uom","uom_dmd"], axis = 1)
medication3 = medication3.set_axis(["nhs_prescribing_agency","emis_drug_guid","authorisedissues_authorised_date","authorisedissues_first_issue_date","cancellation_reason","emis_code_id","confidential_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","dose","emis_medication_status","dummy_patient_flag","duration_in_days","duration_uom","effective_date","effective_date_precision","emis_issue_method","emis_mostrecent_issue_date","emis_prescription_type","emis_registration_organisation_guid","emis_encounter_guid","exa_encounter_guid","end_date","emis_enteredby_userinrole_guid","exa_prescription_guid","estimated_nhs_cost","exa_drug_guid","medication_guid","exa_medication_guid","fhir_medication_intent","exa_mostrecent_issue_date","max_nextissue_days","min_nextissue_days","non_regular_and_current_active_flag","number_authorised","number_of_issues","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","emis_medication_organisation_guid","other_code","other_code_system","prescribed_as_contraceptive_flag","privately_prescribed_flag","quantity","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","reimburse_type","review_date","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","fhir_medication_status","cancellation_date","nhs_prescription_type","uom","uom_dmd"], axis = 1)
medication4 = medication4.set_axis(["nhs_prescribing_agency","emis_drug_guid","authorisedissues_authorised_date","authorisedissues_first_issue_date","cancellation_reason","emis_code_id","confidential_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","dose","emis_medication_status","dummy_patient_flag","duration_in_days","duration_uom","effective_date","effective_date_precision","emis_issue_method","emis_mostrecent_issue_date","emis_prescription_type","emis_registration_organisation_guid","emis_encounter_guid","exa_encounter_guid","end_date","emis_enteredby_userinrole_guid","exa_prescription_guid","estimated_nhs_cost","exa_drug_guid","medication_guid","exa_medication_guid","fhir_medication_intent","exa_mostrecent_issue_date","max_nextissue_days","min_nextissue_days","non_regular_and_current_active_flag","number_authorised","number_of_issues","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","emis_medication_organisation_guid","other_code","other_code_system","prescribed_as_contraceptive_flag","privately_prescribed_flag","quantity","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","reimburse_type","review_date","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","fhir_medication_status","cancellation_date","nhs_prescription_type","uom","uom_dmd"], axis = 1)
medication5 = medication5.set_axis(["nhs_prescribing_agency","emis_drug_guid","authorisedissues_authorised_date","authorisedissues_first_issue_date","cancellation_reason","emis_code_id","confidential_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","dose","emis_medication_status","dummy_patient_flag","duration_in_days","duration_uom","effective_date","effective_date_precision","emis_issue_method","emis_mostrecent_issue_date","emis_prescription_type","emis_registration_organisation_guid","emis_encounter_guid","exa_encounter_guid","end_date","emis_enteredby_userinrole_guid","exa_prescription_guid","estimated_nhs_cost","exa_drug_guid","medication_guid","exa_medication_guid","fhir_medication_intent","exa_mostrecent_issue_date","max_nextissue_days","min_nextissue_days","non_regular_and_current_active_flag","number_authorised","number_of_issues","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","emis_medication_organisation_guid","other_code","other_code_system","prescribed_as_contraceptive_flag","privately_prescribed_flag","quantity","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","reimburse_type","review_date","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","fhir_medication_status","cancellation_date","nhs_prescription_type","uom","uom_dmd"], axis = 1)
medication6 = medication6.set_axis(["nhs_prescribing_agency","emis_drug_guid","authorisedissues_authorised_date","authorisedissues_first_issue_date","cancellation_reason","emis_code_id","confidential_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","dose","emis_medication_status","dummy_patient_flag","duration_in_days","duration_uom","effective_date","effective_date_precision","emis_issue_method","emis_mostrecent_issue_date","emis_prescription_type","emis_registration_organisation_guid","emis_encounter_guid","exa_encounter_guid","end_date","emis_enteredby_userinrole_guid","exa_prescription_guid","estimated_nhs_cost","exa_drug_guid","medication_guid","exa_medication_guid","fhir_medication_intent","exa_mostrecent_issue_date","max_nextissue_days","min_nextissue_days","non_regular_and_current_active_flag","number_authorised","number_of_issues","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","emis_medication_organisation_guid","other_code","other_code_system","prescribed_as_contraceptive_flag","privately_prescribed_flag","quantity","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","reimburse_type","review_date","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","fhir_medication_status","cancellation_date","nhs_prescription_type","uom","uom_dmd"], axis = 1)
medication7 = medication7.set_axis(["nhs_prescribing_agency","emis_drug_guid","authorisedissues_authorised_date","authorisedissues_first_issue_date","cancellation_reason","emis_code_id","confidential_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","dose","emis_medication_status","dummy_patient_flag","duration_in_days","duration_uom","effective_date","effective_date_precision","emis_issue_method","emis_mostrecent_issue_date","emis_prescription_type","emis_registration_organisation_guid","emis_encounter_guid","exa_encounter_guid","end_date","emis_enteredby_userinrole_guid","exa_prescription_guid","estimated_nhs_cost","exa_drug_guid","medication_guid","exa_medication_guid","fhir_medication_intent","exa_mostrecent_issue_date","max_nextissue_days","min_nextissue_days","non_regular_and_current_active_flag","number_authorised","number_of_issues","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","emis_medication_organisation_guid","other_code","other_code_system","prescribed_as_contraceptive_flag","privately_prescribed_flag","quantity","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","reimburse_type","review_date","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","fhir_medication_status","cancellation_date","nhs_prescription_type","uom","uom_dmd"], axis = 1)
medication8 = medication8.set_axis(["nhs_prescribing_agency","emis_drug_guid","authorisedissues_authorised_date","authorisedissues_first_issue_date","cancellation_reason","emis_code_id","confidential_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","dose","emis_medication_status","dummy_patient_flag","duration_in_days","duration_uom","effective_date","effective_date_precision","emis_issue_method","emis_mostrecent_issue_date","emis_prescription_type","emis_registration_organisation_guid","emis_encounter_guid","exa_encounter_guid","end_date","emis_enteredby_userinrole_guid","exa_prescription_guid","estimated_nhs_cost","exa_drug_guid","medication_guid","exa_medication_guid","fhir_medication_intent","exa_mostrecent_issue_date","max_nextissue_days","min_nextissue_days","non_regular_and_current_active_flag","number_authorised","number_of_issues","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","emis_medication_organisation_guid","other_code","other_code_system","prescribed_as_contraceptive_flag","privately_prescribed_flag","quantity","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","reimburse_type","review_date","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","fhir_medication_status","cancellation_date","nhs_prescription_type","uom","uom_dmd"], axis = 1)
medication9 = medication9.set_axis(["nhs_prescribing_agency","emis_drug_guid","authorisedissues_authorised_date","authorisedissues_first_issue_date","cancellation_reason","emis_code_id","confidential_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","dose","emis_medication_status","dummy_patient_flag","duration_in_days","duration_uom","effective_date","effective_date_precision","emis_issue_method","emis_mostrecent_issue_date","emis_prescription_type","emis_registration_organisation_guid","emis_encounter_guid","exa_encounter_guid","end_date","emis_enteredby_userinrole_guid","exa_prescription_guid","estimated_nhs_cost","exa_drug_guid","medication_guid","exa_medication_guid","fhir_medication_intent","exa_mostrecent_issue_date","max_nextissue_days","min_nextissue_days","non_regular_and_current_active_flag","number_authorised","number_of_issues","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","emis_medication_organisation_guid","other_code","other_code_system","prescribed_as_contraceptive_flag","privately_prescribed_flag","quantity","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","reimburse_type","review_date","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","fhir_medication_status","cancellation_date","nhs_prescription_type","uom","uom_dmd"], axis = 1)
medication10 = medication10.set_axis(["nhs_prescribing_agency","emis_drug_guid","authorisedissues_authorised_date","authorisedissues_first_issue_date","cancellation_reason","emis_code_id","confidential_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","dose","emis_medication_status","dummy_patient_flag","duration_in_days","duration_uom","effective_date","effective_date_precision","emis_issue_method","emis_mostrecent_issue_date","emis_prescription_type","emis_registration_organisation_guid","emis_encounter_guid","exa_encounter_guid","end_date","emis_enteredby_userinrole_guid","exa_prescription_guid","estimated_nhs_cost","exa_drug_guid","medication_guid","exa_medication_guid","fhir_medication_intent","exa_mostrecent_issue_date","max_nextissue_days","min_nextissue_days","non_regular_and_current_active_flag","number_authorised","number_of_issues","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","emis_medication_organisation_guid","other_code","other_code_system","prescribed_as_contraceptive_flag","privately_prescribed_flag","quantity","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","reimburse_type","review_date","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","fhir_medication_status","cancellation_date","nhs_prescription_type","uom","uom_dmd"], axis = 1)
medication11 = medication11.set_axis(["nhs_prescribing_agency","emis_drug_guid","authorisedissues_authorised_date","authorisedissues_first_issue_date","cancellation_reason","emis_code_id","confidential_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","dose","emis_medication_status","dummy_patient_flag","duration_in_days","duration_uom","effective_date","effective_date_precision","emis_issue_method","emis_mostrecent_issue_date","emis_prescription_type","emis_registration_organisation_guid","emis_encounter_guid","exa_encounter_guid","end_date","emis_enteredby_userinrole_guid","exa_prescription_guid","estimated_nhs_cost","exa_drug_guid","medication_guid","exa_medication_guid","fhir_medication_intent","exa_mostrecent_issue_date","max_nextissue_days","min_nextissue_days","non_regular_and_current_active_flag","number_authorised","number_of_issues","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","emis_medication_organisation_guid","other_code","other_code_system","prescribed_as_contraceptive_flag","privately_prescribed_flag","quantity","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","reimburse_type","review_date","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","fhir_medication_status","cancellation_date","nhs_prescription_type","uom","uom_dmd"], axis = 1)
medication12 = medication12.set_axis(["nhs_prescribing_agency","emis_drug_guid","authorisedissues_authorised_date","authorisedissues_first_issue_date","cancellation_reason","emis_code_id","confidential_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","dose","emis_medication_status","dummy_patient_flag","duration_in_days","duration_uom","effective_date","effective_date_precision","emis_issue_method","emis_mostrecent_issue_date","emis_prescription_type","emis_registration_organisation_guid","emis_encounter_guid","exa_encounter_guid","end_date","emis_enteredby_userinrole_guid","exa_prescription_guid","estimated_nhs_cost","exa_drug_guid","medication_guid","exa_medication_guid","fhir_medication_intent","exa_mostrecent_issue_date","max_nextissue_days","min_nextissue_days","non_regular_and_current_active_flag","number_authorised","number_of_issues","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","emis_medication_organisation_guid","other_code","other_code_system","prescribed_as_contraceptive_flag","privately_prescribed_flag","quantity","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","reimburse_type","review_date","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","fhir_medication_status","cancellation_date","nhs_prescription_type","uom","uom_dmd"], axis = 1)
medication13 = medication13.set_axis(["nhs_prescribing_agency","emis_drug_guid","authorisedissues_authorised_date","authorisedissues_first_issue_date","cancellation_reason","emis_code_id","confidential_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","dose","emis_medication_status","dummy_patient_flag","duration_in_days","duration_uom","effective_date","effective_date_precision","emis_issue_method","emis_mostrecent_issue_date","emis_prescription_type","emis_registration_organisation_guid","emis_encounter_guid","exa_encounter_guid","end_date","emis_enteredby_userinrole_guid","exa_prescription_guid","estimated_nhs_cost","exa_drug_guid","medication_guid","exa_medication_guid","fhir_medication_intent","exa_mostrecent_issue_date","max_nextissue_days","min_nextissue_days","non_regular_and_current_active_flag","number_authorised","number_of_issues","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","emis_medication_organisation_guid","other_code","other_code_system","prescribed_as_contraceptive_flag","privately_prescribed_flag","quantity","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","reimburse_type","review_date","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","fhir_medication_status","cancellation_date","nhs_prescription_type","uom","uom_dmd"], axis = 1)
medication14 = medication14.set_axis(["nhs_prescribing_agency","emis_drug_guid","authorisedissues_authorised_date","authorisedissues_first_issue_date","cancellation_reason","emis_code_id","confidential_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","dose","emis_medication_status","dummy_patient_flag","duration_in_days","duration_uom","effective_date","effective_date_precision","emis_issue_method","emis_mostrecent_issue_date","emis_prescription_type","emis_registration_organisation_guid","emis_encounter_guid","exa_encounter_guid","end_date","emis_enteredby_userinrole_guid","exa_prescription_guid","estimated_nhs_cost","exa_drug_guid","medication_guid","exa_medication_guid","fhir_medication_intent","exa_mostrecent_issue_date","max_nextissue_days","min_nextissue_days","non_regular_and_current_active_flag","number_authorised","number_of_issues","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","emis_medication_organisation_guid","other_code","other_code_system","prescribed_as_contraceptive_flag","privately_prescribed_flag","quantity","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","reimburse_type","review_date","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","fhir_medication_status","cancellation_date","nhs_prescription_type","uom","uom_dmd"], axis = 1)

medication_list = [medication0,medication1,medication2,medication3,medication4,medication5,medication6,medication7,medication8,medication9,medication10,medication11,medication12,medication13,medication14]

medication_table = pd.concat(medication_list)

medication_table

C:\Users\User\AppData\Local\Temp\ipykernel_17036\2859640830.py:23: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  medication_table = pd.concat(medication_list)

,nhs_prescribing_agency,emis_drug_guid,authorisedissues_authorised_date,authorisedissues_first_issue_date,cancellation_reason,emis_code_id,confidential_flag,consultation_source_emis_code_id,consultation_source_emis_original_term,dose,...,emis_original_term,sensitive_flag,sensitive_patient_flag,snomed_concept_id,snomed_description_id,fhir_medication_status,cancellation_date,nhs_prescription_type,uom,uom_dmd
1,prescribed-at-gp-practice,NaN,2005-04-13 00:00:00,2005-04-13 00:00:00,NaN,266241000033110,false,NaN,NaN,APPLY TWICE A DAY,...,Clotrimazole 1% cream,false,false,326203005,107737701000001118,completed,NaN,acute,gram(s),NaN
2,prescribed-at-gp-practice,NaN,2007-08-15 00:00:00,2007-08-15 00:00:00,NaN,3943341000033113,false,NaN,NaN,2 PUFFS BD,...,Clenil Modulite 100micrograms/dose inhaler (Ch...,false,false,10618211000001109,52438301000001111,active,NaN,repeat,inhaler,NaN
3,prescribed-at-gp-practice,NaN,2005-05-10 00:00:00,2005-05-10 00:00:00,NaN,2215141000033110,false,NaN,NaN,5 MLS QDS,...,Paracetamol 250mg/5ml oral suspension sugar free,false,false,39024611000001102,1615391000001112,completed,NaN,acute,ml,NaN
4,prescribed-at-gp-practice,NaN,2008-03-13 00:00:00,2008-03-13 00:00:00,NaN,849641000033117,false,NaN,NaN,5 MLS OD,...,Loratadine 5mg/5ml oral solution,false,false,38896711000001106,1574471000001116,completed,NaN,acute,ml,NaN
5,prescribed-at-gp-practice,NaN,2008-06-14 00:00:00,2008-06-14 00:00:00,NaN,1467541000033114,false,NaN,NaN,10 MLS BD,...,Trimethoprim 50mg/5ml oral suspension sugar free,false,false,39022311000001100,1614851000001112,completed,NaN,acute,ml,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15058,prescribed-at-gp-practice,23DC3B2A-8984-4EDA-98B9-CFB9D2ECF361,NaN,NaN,NaN,838041000033116,False,NaN,NaN,TAKE ONE DAILY,...,Lisinopril Tablets 20 mg,False,False,318860005.0,56974901000001120.0,completed,NaN,repeat,tablet(s),NaN
15059,prescribed-at-gp-practice,AD382A01-3034-4EC9-9494-285CE5239AF1,NaN,NaN,NaN,1418941000033115,False,NaN,NaN,AS DIRECTED,...,Tetanus Immunoglobulin Injection 250 iu/ml p...,False,False,9478811000001102.0,30981401000001116.0,completed,NaN,acute,pre-filled syrg(s),NaN
15060,prescribed-at-gp-practice,9A4F1F64-F209-40BC-B529-C803E85821C4,NaN,NaN,NaN,91141000033119,False,NaN,NaN,OD,...,Atenolol Tablets 50 mg,False,False,318420003.0,56911901000001112.0,completed,NaN,repeat,tablet,NaN
15061,prescribed-at-gp-practice,97C9D388-B65D-4CD5-9B3F-0BAB037F14D2,NaN,NaN,NaN,1563241000033113,False,NaN,NaN,ONE NIGHT,...,Zopiclone Tablets 7.5 mg,False,False,321175006.0,56913501000001120.0,completed,NaN,repeat,tablet(s),NaN
15062,prescribed-at-gp-practice,234C68C2-00C9-4CF2-A301-7120D39214D1,NaN,NaN,NaN,3196841000033116,False,NaN,NaN,AS DIRECTED,...,Fortisip Bottle Liquid Feed (Mixed Flavours) ...,False,False,NaN,NaN,completed,NaN,repeat,bottle(s),NaN

In [58]:
psql.sqldf("""SELECT * FROM observation_table""")

,abnormal,emis_code_id,comparator,confidential_flag,confidential_patient_flag,consultation_source_emis_code_id,consultation_source_emis_original_term,document_guid,dummy_patient_flag,effective_date,...,sensitive_patient_flag,snomed_concept_id,snomed_description_id,emis_parent_observation_guid,exa_parent_observation_guid,uom,uom_ucum,user_selected,numericvalue,value_pq_2
0,false,253669010,None,false,false,1672871000006114,Main Surgery,None,false,2003-11-21 00:00:00,...,false,248333004,370729019,None,None,cm,cm,None,150.000,None
1,false,173141000006118,None,false,false,1672871000006114,Main Surgery,None,false,2004-12-30 00:00:00,...,false,182918009,173141000006118,None,None,None,None,None,None,None
2,false,137851000000113,None,false,false,1672871000006114,Main Surgery,None,false,2003-09-17 00:00:00,...,false,88551000000109,137851000000113,None,None,None,None,None,None,None
3,false,619931000006119,None,false,false,None,None,None,false,2006-08-20 00:00:00,...,false,1091811000000102,2734671000000117,C1286EE9-FC69-9394-51E7-F14729E08CF1,d20a59e5-dab5-581c-aea2-04d5d8a61b34,mm Hg,None,None,77.000,None
4,false,102928018,None,false,false,None,None,None,false,2006-10-22 00:00:00,...,false,1022651000000100,2553501000000111,None,None,x10^9/L,None,None,636.000,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275760,0,144821000006115,None,0,0,None,None,None,0,2003-02-22 00:00:00,...,0,1000651000000109,2573011000000117,E27A80E6-064F-4C9B-BF5C-C2E0956F345E,7e8d2932-9150-5b7f-8016-933f86a340c4,mmol/L,mmol/L,None,4.5,None
275761,0,397211016,None,0,0,None,None,None,0,2021-11-15 00:00:00,...,0,3457005,18841000006116,None,None,None,None,None,None,None
275762,0,11561000000115,None,0,0,1.67287100000611e+15,Main Surgery,None,0,2001-09-29 00:00:00,...,0,1331000000103,1596371000000114,None,None,None,None,None,None,None
275763,1,1488841016,None,0,0,1.67287100000611e+15,General Practice Surgery,None,0,2001-03-27 00:00:00,...,0,1014641000000102,2579001000000116,None,None,None,None,None,None,None
275764,1,1488841016,None,0,0,1.67287100000611e+15,General Practice Surgery,None,0,2005-01-14 00:00:00,...,0,1014641000000102,2579001000000116,None,None,None,None,None,None,None

In [61]:
patient

,age,postcode,patient_surname,patient_givenname,date_of_birth,date_of_death,registration_guid,patient_id,gender
0,0,HX2 8WG,Bibi,Maureen,2023-02-11 00:00:00,NaN,9A70C9CD-D0F7-43F3-A05C-34C8F192E00C,10457,Female
1,0,LS10 8MH,O'Brien,Karen,2022-11-08 00:00:00,NaN,57E3019C-25E6-4591-AA6D-3139AF37DC3F,11488,Female
2,0,WF17 2XU,Turner,Mark,2023-01-28 00:00:00,NaN,A1700F02-134E-42FF-B537-1B7DA00F8C25,9844,Male
3,0,WF13 3RJ,Law,Frederick,2022-12-05 00:00:00,NaN,CEDE39B9-9261-4B21-9E07-92D4308E87D5,9972,Male
4,0,LS99 9ZZ,Connor,Emerald,2022-11-17 00:00:00,NaN,9532DEBE-42CC-40E4-820A-55DF603E0D23,18955,Indeterminate
...,...,...,...,...,...,...,...,...,...
4538,0,LS99 9ZZ,Lyons,Ahmir,2023-01-08 00:00:00,NaN,61CE65F5-271B-4151-8700-70DE00CC0A9B,29589,Female
4539,0,LS99 9ZZ,Williamson,Cyrus,2023-02-09 00:00:00,NaN,4C16CFF4-520C-4B1C-8B03-9B214BDFAC76,19592,Female
4540,0,LS99 9ZZ,Healy,Kamari,2022-12-10 00:00:00,NaN,21107E5F-CE16-4669-9B6E-43671212E9D0,27505,Indeterminate
4541,0,LS99 9ZZ,Bolton,Zachariah,2022-11-23 00:00:00,NaN,9F8F0E53-7252-4998-A035-6809941C8A83,30629,Male
4542,0,LS99 9ZZ,Johnson,Adrianna,2022-12-05 00:00:00,NaN,F2E5C6F8-52B3-477B-83B2-955A9BB227A5,26947,Female

In [96]:
# Solution 1

psql.sqldf("""
           SELECT SUBSTR(postcode,1,2) AS 'Area',
           COUNT(case when gender = 'Male' then 1 end) AS 'Male',
           COUNT(case when gender = 'Female' then 1 end) AS 'Female',
           COUNT(case when gender = 'Indeterminate' then 1 end) AS 'Indeterminate',
           COUNT(case when gender = 'Unknown' then 1 end) AS 'Unknown',
           COUNT(*) AS 'Total'
           FROM patient
           GROUP BY Area
           ORDER BY Total DESC""")
# psql.sqldf("""
# SELECT gender,COUNT(gender) AS 'Count' FROM patient
# GROUP BY gender """)

    Area  Male  Female  Indeterminate  Unknown  Total
0     LS   873     902            435      430   2640
1     WF   289     281              0        0    570
2     BD   258     265              0        0    523
3     HX   142     131              0        0    273
4     HD   120      97              0        0    217
5   None    57      41              4        3    105
6     S7    30      25              0        0     55
7     OL    15      23              0        0     38
8     BS    11      14              1        0     26
9     SE     8       8              0        0     16
10    N1     5       3              0        0      8
11    WR     4       2              1        0      7
12    TF     4       0              0        0      4
13    SN     3       1              0        0      4
14    HP     1       3              0        0      4
15    W2     0       3              0        0      3
16    SW     1       2              0        0      3
17    S3     1       2              0        0      3
18    EC     1       2              0        0      3
19    CF     3       0              0        0      3
20    W3     1       1              0        0      2
21    SO     2       0              0        0      2
22    NR     0       2              0        0      2
23    NE     1       1              0        0      2
24    AY     1       1              0        0      2
25    YO     1       0              0        0      1
26    XX     1       0              0        0      1
27    W1     0       1              0        0      1
28    UB     0       1              0        0      1
29    SA     1       0              0        0      1
30    S2     0       1              0        0      1
31    S1     1       0              0        0      1
32    OX     1       0              0        0      1
33    OH     1       0              0        0      1
34    NT     0       0              1        0      1
35    NP     1       0              0        0      1
36    NB     1       0              0        0      1
37    N2     0       1              0        0      1
38    MK     0       1              0        0      1
39    M6     1       0              0        0      1
40    LL     0       1              0        0      1
41    LA     0       1              0        0      1
42    G4     0       1              0        0      1
43    G2     0       1              0        0      1
44    EX     0       1              0        0      1
45    EH     0       0              0        1      1
46    E1     0       1              0        0      1
47    DE     0       1              0        0      1
48    BN     0       1              0        0      1
49    BB     1       0              0        0      1
50    BA     0       1              0        0      1
51    B1     0       1              0        0      1
52    AN     1       0              0        0      1

In [112]:
psql.sqldf("""
           SELECT p.registration_guid, p.patient_id, p.patient_surname, p.patient_givenname, p.postcode, p.age, p.gender
           FROM patient p
           INNER JOIN medication_table m ON (m.registration_guid=p.registration_guid)
           """)

,registration_guid,patient_id,patient_surname,patient_givenname,postcode,age,gender
0,9A70C9CD-D0F7-43F3-A05C-34C8F192E00C,10457,Bibi,Maureen,HX2 8WG,0,Female
1,9A70C9CD-D0F7-43F3-A05C-34C8F192E00C,10457,Bibi,Maureen,HX2 8WG,0,Female
2,9A70C9CD-D0F7-43F3-A05C-34C8F192E00C,10457,Bibi,Maureen,HX2 8WG,0,Female
3,9A70C9CD-D0F7-43F3-A05C-34C8F192E00C,10457,Bibi,Maureen,HX2 8WG,0,Female
4,9A70C9CD-D0F7-43F3-A05C-34C8F192E00C,10457,Bibi,Maureen,HX2 8WG,0,Female
...,...,...,...,...,...,...,...
214011,6D3A2201-4791-419D-A025-A6D62DF28136,11368,Schofield,Neil,LS28 3VF,0,Male
214012,6D3A2201-4791-419D-A025-A6D62DF28136,11368,Schofield,Neil,LS28 3VF,0,Male
214013,6D3A2201-4791-419D-A025-A6D62DF28136,11368,Schofield,Neil,LS28 3VF,0,Male
214014,40679503-39DB-4BA9-B927-E508448B371D,12413,Savage,Claire,WF10 6GL,0,Female
214015,40679503-39DB-4BA9-B927-E508448B371D,12413,Savage,Claire,WF10 6GL,0,Female

In [108]:
patient

,age,postcode,patient_surname,patient_givenname,date_of_birth,date_of_death,registration_guid,patient_id,gender
0,0,HX2 8WG,Bibi,Maureen,2023-02-11 00:00:00,NaN,9A70C9CD-D0F7-43F3-A05C-34C8F192E00C,10457,Female
1,0,LS10 8MH,O'Brien,Karen,2022-11-08 00:00:00,NaN,57E3019C-25E6-4591-AA6D-3139AF37DC3F,11488,Female
2,0,WF17 2XU,Turner,Mark,2023-01-28 00:00:00,NaN,A1700F02-134E-42FF-B537-1B7DA00F8C25,9844,Male
3,0,WF13 3RJ,Law,Frederick,2022-12-05 00:00:00,NaN,CEDE39B9-9261-4B21-9E07-92D4308E87D5,9972,Male
4,0,LS99 9ZZ,Connor,Emerald,2022-11-17 00:00:00,NaN,9532DEBE-42CC-40E4-820A-55DF603E0D23,18955,Indeterminate
...,...,...,...,...,...,...,...,...,...
4538,0,LS99 9ZZ,Lyons,Ahmir,2023-01-08 00:00:00,NaN,61CE65F5-271B-4151-8700-70DE00CC0A9B,29589,Female
4539,0,LS99 9ZZ,Williamson,Cyrus,2023-02-09 00:00:00,NaN,4C16CFF4-520C-4B1C-8B03-9B214BDFAC76,19592,Female
4540,0,LS99 9ZZ,Healy,Kamari,2022-12-10 00:00:00,NaN,21107E5F-CE16-4669-9B6E-43671212E9D0,27505,Indeterminate
4541,0,LS99 9ZZ,Bolton,Zachariah,2022-11-23 00:00:00,NaN,9F8F0E53-7252-4998-A035-6809941C8A83,30629,Male
4542,0,LS99 9ZZ,Johnson,Adrianna,2022-12-05 00:00:00,NaN,F2E5C6F8-52B3-477B-83B2-955A9BB227A5,26947,Female

In [107]:
clinical_codes

,refset_simple_id,parent_code_id,code_id,snomed_concept_id,emis_term
0,9.990129e+17,NaN,9315231000006113,1.067599e+16,Acute severe exacerbation of mild persistent a...
1,9.990129e+17,NaN,301451010,1.959490e+08,Chronic wheezy bronchitis
2,9.990116e+17,NaN,7627141000006111,7.080300e+08,Pulmonary emphysema co-occurrent with fibrosis...
3,9.990129e+17,NaN,13844351000006118,7.039540e+08,"Asthma caused by house dust mite, Dermatophago..."
4,9.990116e+17,NaN,506053014,8.440900e+07,Purulent chronic bronchitis
...,...,...,...,...,...
581,9.990116e+17,NaN,139979010,8.440900e+07,Fetid chronic bronchitis
582,9.990116e+17,NaN,3921361000006112,8.743300e+07,Emphysema of lung
583,NaN,1.223821e+15,9299341000033119,NaN,Olodaterol 2.5micrograms/dose solution for inh...
584,NaN,7.173210e+14,3164141000033119,NaN,Fluticasone propionate 250micrograms/dose / Sa...
585,NaN,5.912210e+14,9995641000033112,NaN,Aclidinium bromide 396micrograms/dose / Formot...

In [84]:
medication_table

,nhs_prescribing_agency,emis_drug_guid,authorisedissues_authorised_date,authorisedissues_first_issue_date,cancellation_reason,emis_code_id,confidential_flag,consultation_source_emis_code_id,consultation_source_emis_original_term,dose,...,emis_original_term,sensitive_flag,sensitive_patient_flag,snomed_concept_id,snomed_description_id,fhir_medication_status,cancellation_date,nhs_prescription_type,uom,uom_dmd
4,prescribed-at-gp-practice,NaN,2008-03-13 00:00:00,2008-03-13 00:00:00,NaN,849641000033117,false,NaN,NaN,5 MLS OD,...,Loratadine 5mg/5ml oral solution,false,false,38896711000001106,1574471000001116,completed,NaN,acute,ml,NaN
5,prescribed-at-gp-practice,NaN,2008-06-14 00:00:00,2008-06-14 00:00:00,NaN,1467541000033114,false,NaN,NaN,10 MLS BD,...,Trimethoprim 50mg/5ml oral suspension sugar free,false,false,39022311000001100,1614851000001112,completed,NaN,acute,ml,NaN
6,prescribed-at-gp-practice,NaN,2008-06-05 00:00:00,2008-06-05 00:00:00,NaN,1467541000033114,false,NaN,NaN,10ML BD,...,Trimethoprim 50mg/5ml oral suspension sugar free,false,false,39022311000001100,1614851000001112,completed,NaN,acute,ml,NaN
7,prescribed-at-gp-practice,NaN,2007-08-15 00:00:00,2007-08-15 00:00:00,NaN,2804441000033110,false,NaN,NaN,AS DIRECTED,...,AeroChamber Plus (Trudell Medical UK Ltd),false,false,9516911000001109,106215701000001110,completed,NaN,acute,device,NaN
8,prescribed-at-gp-practice,NaN,2005-05-10 00:00:00,2005-05-10 00:00:00,NaN,1739441000033117,false,NaN,NaN,5 MLS QDS,...,Ibuprofen 100mg/5ml oral suspension sugar free,false,false,39108111000001104,1674861000001115,completed,NaN,acute,ml,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15058,prescribed-at-gp-practice,23DC3B2A-8984-4EDA-98B9-CFB9D2ECF361,NaN,NaN,NaN,838041000033116,False,NaN,NaN,TAKE ONE DAILY,...,Lisinopril Tablets 20 mg,False,False,318860005.0,56974901000001120.0,completed,NaN,repeat,tablet(s),NaN
15059,prescribed-at-gp-practice,AD382A01-3034-4EC9-9494-285CE5239AF1,NaN,NaN,NaN,1418941000033115,False,NaN,NaN,AS DIRECTED,...,Tetanus Immunoglobulin Injection 250 iu/ml p...,False,False,9478811000001102.0,30981401000001116.0,completed,NaN,acute,pre-filled syrg(s),NaN
15060,prescribed-at-gp-practice,9A4F1F64-F209-40BC-B529-C803E85821C4,NaN,NaN,NaN,91141000033119,False,NaN,NaN,OD,...,Atenolol Tablets 50 mg,False,False,318420003.0,56911901000001112.0,completed,NaN,repeat,tablet,NaN
15061,prescribed-at-gp-practice,97C9D388-B65D-4CD5-9B3F-0BAB037F14D2,NaN,NaN,NaN,1563241000033113,False,NaN,NaN,ONE NIGHT,...,Zopiclone Tablets 7.5 mg,False,False,321175006.0,56913501000001120.0,completed,NaN,repeat,tablet(s),NaN
15062,prescribed-at-gp-practice,234C68C2-00C9-4CF2-A301-7120D39214D1,NaN,NaN,NaN,3196841000033116,False,NaN,NaN,AS DIRECTED,...,Fortisip Bottle Liquid Feed (Mixed Flavours) ...,False,False,NaN,NaN,completed,NaN,repeat,bottle(s),NaN

In [82]:
# Solution 2
psql.sqldf("""
           SELECT postcode,
           COUNT(case when gender = 'Male' then 1 end) AS 'Male',
           COUNT(case when gender = 'Female' then 1 end) AS 'Female',
           COUNT(case when gender = 'Indeterminate' then 1 end) AS 'Indeterminate',
           COUNT(case when gender = 'Unknown' then 1 end) AS 'Unknown',
           COUNT(*) AS 'Total'
           FROM patient
           GROUP BY postcode
           ORDER BY Total DESC""")

,age,postcode,patient_surname,patient_givenname,date_of_birth,date_of_death,registration_guid,patient_id,gender
0,0,HX2 8WG,Bibi,Maureen,2023-02-11 00:00:00,NaN,9A70C9CD-D0F7-43F3-A05C-34C8F192E00C,10457,Female
1,0,LS10 8MH,O'Brien,Karen,2022-11-08 00:00:00,NaN,57E3019C-25E6-4591-AA6D-3139AF37DC3F,11488,Female
2,0,WF17 2XU,Turner,Mark,2023-01-28 00:00:00,NaN,A1700F02-134E-42FF-B537-1B7DA00F8C25,9844,Male
3,0,WF13 3RJ,Law,Frederick,2022-12-05 00:00:00,NaN,CEDE39B9-9261-4B21-9E07-92D4308E87D5,9972,Male
4,0,LS99 9ZZ,Connor,Emerald,2022-11-17 00:00:00,NaN,9532DEBE-42CC-40E4-820A-55DF603E0D23,18955,Indeterminate
...,...,...,...,...,...,...,...,...,...
4538,0,LS99 9ZZ,Lyons,Ahmir,2023-01-08 00:00:00,NaN,61CE65F5-271B-4151-8700-70DE00CC0A9B,29589,Female
4539,0,LS99 9ZZ,Williamson,Cyrus,2023-02-09 00:00:00,NaN,4C16CFF4-520C-4B1C-8B03-9B214BDFAC76,19592,Female
4540,0,LS99 9ZZ,Healy,Kamari,2022-12-10 00:00:00,NaN,21107E5F-CE16-4669-9B6E-43671212E9D0,27505,Indeterminate
4541,0,LS99 9ZZ,Bolton,Zachariah,2022-11-23 00:00:00,NaN,9F8F0E53-7252-4998-A035-6809941C8A83,30629,Male
4542,0,LS99 9ZZ,Johnson,Adrianna,2022-12-05 00:00:00,NaN,F2E5C6F8-52B3-477B-83B2-955A9BB227A5,26947,Female