In [2]:
# Jupyter notebook
import pandas as pd
import pandasql as psql
import glob

In [3]:
clinical_codes = pd.read_csv(r'../exa-data-analyst-assessment/data/clinical_codes.csv',dtype='str')
patient = pd.read_csv(r'../exa-data-analyst-assessment/data/patient.csv',dtype='str')

In [4]:
# Creates a varaible name for each medication file in folder [medication1, medication2, ... ,medicationx]

# Note that variables 0 to 14 are now mapped to filenames 1, 10, 11, 12, 13, 14, 15, 2, 3, 4, 5, 6, 7, 8, 9 respectively

medication_list = glob.glob(r'../exa-data-analyst-assessment/data/medication/*.csv')
for n, val in enumerate(medication_list):
    globals()["medication%d"%n] = pd.read_csv(val, header=None,dtype='str')

# Creates a variable name for each observation file in folder [observation1, observation2, ..., observationx]

# Note that variables 0 to 11 are now mapped to filenames 1, 10, 11, 12, 2, 3, 4, 5, 6, 7, 8, 9 respectively

observation_list = glob.glob(r'../exa-data-analyst-assessment/data/observation/*.csv')
for n, val in enumerate(observation_list):
    globals()["observation%d"%n] = pd.read_csv(val, header=None,dtype='str')

In [5]:
# Concatenating all observation csvs into one table

observation0 = observation0.iloc[1:] # column names are first row
observation0 = observation0.set_axis(["abnormal","emis_code_id","comparator","confidential_flag","confidential_patient_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","document_guid","dummy_patient_flag","effective_date","effective_date_precision","emis_enteredby_userinrole_guid","emis_episodicity","end_date","fhir_episodicity","emis_observation_guid","exa_observation_guid","fhir_interpretation_code","is_parent_flag","non_regular_and_current_active_flag","emis_observation_id","observation_type","emis_observationtypeid","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","other_code","other_code_system","other_display","range_lower","range_upper","readv2_code","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","emis_parent_observation_guid","exa_parent_observation_guid","uom","uom_ucum","user_selected","numericvalue","value_pq_2"], axis = 1)
observation1 = observation1.set_axis(["abnormal","emis_code_id","comparator","confidential_flag","confidential_patient_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","document_guid","dummy_patient_flag","effective_date","effective_date_precision","emis_enteredby_userinrole_guid","emis_episodicity","end_date","fhir_episodicity","emis_observation_guid","exa_observation_guid","fhir_interpretation_code","is_parent_flag","non_regular_and_current_active_flag","emis_observation_id","observation_type","emis_observationtypeid","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","other_code","other_code_system","other_display","range_lower","range_upper","readv2_code","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","emis_parent_observation_guid","exa_parent_observation_guid","uom","uom_ucum","user_selected","numericvalue","value_pq_2"], axis = 1)
observation2 = observation2.set_axis(["abnormal","emis_code_id","comparator","confidential_flag","confidential_patient_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","document_guid","dummy_patient_flag","effective_date","effective_date_precision","emis_enteredby_userinrole_guid","emis_episodicity","end_date","fhir_episodicity","emis_observation_guid","exa_observation_guid","fhir_interpretation_code","is_parent_flag","non_regular_and_current_active_flag","emis_observation_id","observation_type","emis_observationtypeid","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","other_code","other_code_system","other_display","range_lower","range_upper","readv2_code","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","emis_parent_observation_guid","exa_parent_observation_guid","uom","uom_ucum","user_selected","numericvalue","value_pq_2"], axis = 1)
observation3 = observation3.set_axis(["abnormal","emis_code_id","comparator","confidential_flag","confidential_patient_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","document_guid","dummy_patient_flag","effective_date","effective_date_precision","emis_enteredby_userinrole_guid","emis_episodicity","end_date","fhir_episodicity","emis_observation_guid","exa_observation_guid","fhir_interpretation_code","is_parent_flag","non_regular_and_current_active_flag","emis_observation_id","observation_type","emis_observationtypeid","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","other_code","other_code_system","other_display","range_lower","range_upper","readv2_code","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","emis_parent_observation_guid","exa_parent_observation_guid","uom","uom_ucum","user_selected","numericvalue","value_pq_2"], axis = 1)
observation4 = observation4.set_axis(["abnormal","emis_code_id","comparator","confidential_flag","confidential_patient_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","document_guid","dummy_patient_flag","effective_date","effective_date_precision","emis_enteredby_userinrole_guid","emis_episodicity","end_date","fhir_episodicity","emis_observation_guid","exa_observation_guid","fhir_interpretation_code","is_parent_flag","non_regular_and_current_active_flag","emis_observation_id","observation_type","emis_observationtypeid","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","other_code","other_code_system","other_display","range_lower","range_upper","readv2_code","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","emis_parent_observation_guid","exa_parent_observation_guid","uom","uom_ucum","user_selected","numericvalue","value_pq_2"], axis = 1)
observation5 = observation5.set_axis(["abnormal","emis_code_id","comparator","confidential_flag","confidential_patient_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","document_guid","dummy_patient_flag","effective_date","effective_date_precision","emis_enteredby_userinrole_guid","emis_episodicity","end_date","fhir_episodicity","emis_observation_guid","exa_observation_guid","fhir_interpretation_code","is_parent_flag","non_regular_and_current_active_flag","emis_observation_id","observation_type","emis_observationtypeid","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","other_code","other_code_system","other_display","range_lower","range_upper","readv2_code","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","emis_parent_observation_guid","exa_parent_observation_guid","uom","uom_ucum","user_selected","numericvalue","value_pq_2"], axis = 1)
observation6 = observation6.set_axis(["abnormal","emis_code_id","comparator","confidential_flag","confidential_patient_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","document_guid","dummy_patient_flag","effective_date","effective_date_precision","emis_enteredby_userinrole_guid","emis_episodicity","end_date","fhir_episodicity","emis_observation_guid","exa_observation_guid","fhir_interpretation_code","is_parent_flag","non_regular_and_current_active_flag","emis_observation_id","observation_type","emis_observationtypeid","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","other_code","other_code_system","other_display","range_lower","range_upper","readv2_code","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","emis_parent_observation_guid","exa_parent_observation_guid","uom","uom_ucum","user_selected","numericvalue","value_pq_2"], axis = 1)
observation7 = observation7.set_axis(["abnormal","emis_code_id","comparator","confidential_flag","confidential_patient_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","document_guid","dummy_patient_flag","effective_date","effective_date_precision","emis_enteredby_userinrole_guid","emis_episodicity","end_date","fhir_episodicity","emis_observation_guid","exa_observation_guid","fhir_interpretation_code","is_parent_flag","non_regular_and_current_active_flag","emis_observation_id","observation_type","emis_observationtypeid","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","other_code","other_code_system","other_display","range_lower","range_upper","readv2_code","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","emis_parent_observation_guid","exa_parent_observation_guid","uom","uom_ucum","user_selected","numericvalue","value_pq_2"], axis = 1)
observation8 = observation8.set_axis(["abnormal","emis_code_id","comparator","confidential_flag","confidential_patient_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","document_guid","dummy_patient_flag","effective_date","effective_date_precision","emis_enteredby_userinrole_guid","emis_episodicity","end_date","fhir_episodicity","emis_observation_guid","exa_observation_guid","fhir_interpretation_code","is_parent_flag","non_regular_and_current_active_flag","emis_observation_id","observation_type","emis_observationtypeid","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","other_code","other_code_system","other_display","range_lower","range_upper","readv2_code","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","emis_parent_observation_guid","exa_parent_observation_guid","uom","uom_ucum","user_selected","numericvalue","value_pq_2"], axis = 1)
observation9 = observation9.set_axis(["abnormal","emis_code_id","comparator","confidential_flag","confidential_patient_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","document_guid","dummy_patient_flag","effective_date","effective_date_precision","emis_enteredby_userinrole_guid","emis_episodicity","end_date","fhir_episodicity","emis_observation_guid","exa_observation_guid","fhir_interpretation_code","is_parent_flag","non_regular_and_current_active_flag","emis_observation_id","observation_type","emis_observationtypeid","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","other_code","other_code_system","other_display","range_lower","range_upper","readv2_code","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","emis_parent_observation_guid","exa_parent_observation_guid","uom","uom_ucum","user_selected","numericvalue","value_pq_2"], axis = 1)
observation10 = observation10.set_axis(["abnormal","emis_code_id","comparator","confidential_flag","confidential_patient_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","document_guid","dummy_patient_flag","effective_date","effective_date_precision","emis_enteredby_userinrole_guid","emis_episodicity","end_date","fhir_episodicity","emis_observation_guid","exa_observation_guid","fhir_interpretation_code","is_parent_flag","non_regular_and_current_active_flag","emis_observation_id","observation_type","emis_observationtypeid","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","other_code","other_code_system","other_display","range_lower","range_upper","readv2_code","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","emis_parent_observation_guid","exa_parent_observation_guid","uom","uom_ucum","user_selected","numericvalue","value_pq_2"], axis = 1)
observation11 = observation11.set_axis(["abnormal","emis_code_id","comparator","confidential_flag","confidential_patient_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","document_guid","dummy_patient_flag","effective_date","effective_date_precision","emis_enteredby_userinrole_guid","emis_episodicity","end_date","fhir_episodicity","emis_observation_guid","exa_observation_guid","fhir_interpretation_code","is_parent_flag","non_regular_and_current_active_flag","emis_observation_id","observation_type","emis_observationtypeid","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","other_code","other_code_system","other_display","range_lower","range_upper","readv2_code","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","emis_parent_observation_guid","exa_parent_observation_guid","uom","uom_ucum","user_selected","numericvalue","value_pq_2"], axis = 1)

observation_list = [observation0, observation1, observation2, observation3, observation4, observation5, observation6, observation7, observation8, observation9, observation10, observation11]

observation_table = pd.concat(observation_list)

In [6]:
# Concatenating all medication csvs into one table

medication0 = medication0.iloc[1:] # column names are first row
medication0 = medication0.set_axis(["nhs_prescribing_agency","emis_drug_guid","authorisedissues_authorised_date","authorisedissues_first_issue_date","cancellation_reason","emis_code_id","confidential_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","dose","emis_medication_status","dummy_patient_flag","duration_in_days","duration_uom","effective_date","effective_date_precision","emis_issue_method","emis_mostrecent_issue_date","emis_prescription_type","emis_registration_organisation_guid","emis_encounter_guid","exa_encounter_guid","end_date","emis_enteredby_userinrole_guid","exa_prescription_guid","estimated_nhs_cost","exa_drug_guid","medication_guid","exa_medication_guid","fhir_medication_intent","exa_mostrecent_issue_date","max_nextissue_days","min_nextissue_days","non_regular_and_current_active_flag","number_authorised","number_of_issues","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","emis_medication_organisation_guid","other_code","other_code_system","prescribed_as_contraceptive_flag","privately_prescribed_flag","quantity","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","reimburse_type","review_date","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","fhir_medication_status","cancellation_date","nhs_prescription_type","uom","uom_dmd"], axis = 1)
medication1 = medication1.set_axis(["nhs_prescribing_agency","emis_drug_guid","authorisedissues_authorised_date","authorisedissues_first_issue_date","cancellation_reason","emis_code_id","confidential_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","dose","emis_medication_status","dummy_patient_flag","duration_in_days","duration_uom","effective_date","effective_date_precision","emis_issue_method","emis_mostrecent_issue_date","emis_prescription_type","emis_registration_organisation_guid","emis_encounter_guid","exa_encounter_guid","end_date","emis_enteredby_userinrole_guid","exa_prescription_guid","estimated_nhs_cost","exa_drug_guid","medication_guid","exa_medication_guid","fhir_medication_intent","exa_mostrecent_issue_date","max_nextissue_days","min_nextissue_days","non_regular_and_current_active_flag","number_authorised","number_of_issues","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","emis_medication_organisation_guid","other_code","other_code_system","prescribed_as_contraceptive_flag","privately_prescribed_flag","quantity","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","reimburse_type","review_date","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","fhir_medication_status","cancellation_date","nhs_prescription_type","uom","uom_dmd"], axis = 1)
medication2 = medication2.set_axis(["nhs_prescribing_agency","emis_drug_guid","authorisedissues_authorised_date","authorisedissues_first_issue_date","cancellation_reason","emis_code_id","confidential_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","dose","emis_medication_status","dummy_patient_flag","duration_in_days","duration_uom","effective_date","effective_date_precision","emis_issue_method","emis_mostrecent_issue_date","emis_prescription_type","emis_registration_organisation_guid","emis_encounter_guid","exa_encounter_guid","end_date","emis_enteredby_userinrole_guid","exa_prescription_guid","estimated_nhs_cost","exa_drug_guid","medication_guid","exa_medication_guid","fhir_medication_intent","exa_mostrecent_issue_date","max_nextissue_days","min_nextissue_days","non_regular_and_current_active_flag","number_authorised","number_of_issues","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","emis_medication_organisation_guid","other_code","other_code_system","prescribed_as_contraceptive_flag","privately_prescribed_flag","quantity","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","reimburse_type","review_date","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","fhir_medication_status","cancellation_date","nhs_prescription_type","uom","uom_dmd"], axis = 1)
medication3 = medication3.set_axis(["nhs_prescribing_agency","emis_drug_guid","authorisedissues_authorised_date","authorisedissues_first_issue_date","cancellation_reason","emis_code_id","confidential_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","dose","emis_medication_status","dummy_patient_flag","duration_in_days","duration_uom","effective_date","effective_date_precision","emis_issue_method","emis_mostrecent_issue_date","emis_prescription_type","emis_registration_organisation_guid","emis_encounter_guid","exa_encounter_guid","end_date","emis_enteredby_userinrole_guid","exa_prescription_guid","estimated_nhs_cost","exa_drug_guid","medication_guid","exa_medication_guid","fhir_medication_intent","exa_mostrecent_issue_date","max_nextissue_days","min_nextissue_days","non_regular_and_current_active_flag","number_authorised","number_of_issues","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","emis_medication_organisation_guid","other_code","other_code_system","prescribed_as_contraceptive_flag","privately_prescribed_flag","quantity","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","reimburse_type","review_date","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","fhir_medication_status","cancellation_date","nhs_prescription_type","uom","uom_dmd"], axis = 1)
medication4 = medication4.set_axis(["nhs_prescribing_agency","emis_drug_guid","authorisedissues_authorised_date","authorisedissues_first_issue_date","cancellation_reason","emis_code_id","confidential_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","dose","emis_medication_status","dummy_patient_flag","duration_in_days","duration_uom","effective_date","effective_date_precision","emis_issue_method","emis_mostrecent_issue_date","emis_prescription_type","emis_registration_organisation_guid","emis_encounter_guid","exa_encounter_guid","end_date","emis_enteredby_userinrole_guid","exa_prescription_guid","estimated_nhs_cost","exa_drug_guid","medication_guid","exa_medication_guid","fhir_medication_intent","exa_mostrecent_issue_date","max_nextissue_days","min_nextissue_days","non_regular_and_current_active_flag","number_authorised","number_of_issues","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","emis_medication_organisation_guid","other_code","other_code_system","prescribed_as_contraceptive_flag","privately_prescribed_flag","quantity","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","reimburse_type","review_date","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","fhir_medication_status","cancellation_date","nhs_prescription_type","uom","uom_dmd"], axis = 1)
medication5 = medication5.set_axis(["nhs_prescribing_agency","emis_drug_guid","authorisedissues_authorised_date","authorisedissues_first_issue_date","cancellation_reason","emis_code_id","confidential_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","dose","emis_medication_status","dummy_patient_flag","duration_in_days","duration_uom","effective_date","effective_date_precision","emis_issue_method","emis_mostrecent_issue_date","emis_prescription_type","emis_registration_organisation_guid","emis_encounter_guid","exa_encounter_guid","end_date","emis_enteredby_userinrole_guid","exa_prescription_guid","estimated_nhs_cost","exa_drug_guid","medication_guid","exa_medication_guid","fhir_medication_intent","exa_mostrecent_issue_date","max_nextissue_days","min_nextissue_days","non_regular_and_current_active_flag","number_authorised","number_of_issues","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","emis_medication_organisation_guid","other_code","other_code_system","prescribed_as_contraceptive_flag","privately_prescribed_flag","quantity","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","reimburse_type","review_date","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","fhir_medication_status","cancellation_date","nhs_prescription_type","uom","uom_dmd"], axis = 1)
medication6 = medication6.set_axis(["nhs_prescribing_agency","emis_drug_guid","authorisedissues_authorised_date","authorisedissues_first_issue_date","cancellation_reason","emis_code_id","confidential_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","dose","emis_medication_status","dummy_patient_flag","duration_in_days","duration_uom","effective_date","effective_date_precision","emis_issue_method","emis_mostrecent_issue_date","emis_prescription_type","emis_registration_organisation_guid","emis_encounter_guid","exa_encounter_guid","end_date","emis_enteredby_userinrole_guid","exa_prescription_guid","estimated_nhs_cost","exa_drug_guid","medication_guid","exa_medication_guid","fhir_medication_intent","exa_mostrecent_issue_date","max_nextissue_days","min_nextissue_days","non_regular_and_current_active_flag","number_authorised","number_of_issues","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","emis_medication_organisation_guid","other_code","other_code_system","prescribed_as_contraceptive_flag","privately_prescribed_flag","quantity","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","reimburse_type","review_date","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","fhir_medication_status","cancellation_date","nhs_prescription_type","uom","uom_dmd"], axis = 1)
medication7 = medication7.set_axis(["nhs_prescribing_agency","emis_drug_guid","authorisedissues_authorised_date","authorisedissues_first_issue_date","cancellation_reason","emis_code_id","confidential_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","dose","emis_medication_status","dummy_patient_flag","duration_in_days","duration_uom","effective_date","effective_date_precision","emis_issue_method","emis_mostrecent_issue_date","emis_prescription_type","emis_registration_organisation_guid","emis_encounter_guid","exa_encounter_guid","end_date","emis_enteredby_userinrole_guid","exa_prescription_guid","estimated_nhs_cost","exa_drug_guid","medication_guid","exa_medication_guid","fhir_medication_intent","exa_mostrecent_issue_date","max_nextissue_days","min_nextissue_days","non_regular_and_current_active_flag","number_authorised","number_of_issues","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","emis_medication_organisation_guid","other_code","other_code_system","prescribed_as_contraceptive_flag","privately_prescribed_flag","quantity","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","reimburse_type","review_date","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","fhir_medication_status","cancellation_date","nhs_prescription_type","uom","uom_dmd"], axis = 1)
medication8 = medication8.set_axis(["nhs_prescribing_agency","emis_drug_guid","authorisedissues_authorised_date","authorisedissues_first_issue_date","cancellation_reason","emis_code_id","confidential_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","dose","emis_medication_status","dummy_patient_flag","duration_in_days","duration_uom","effective_date","effective_date_precision","emis_issue_method","emis_mostrecent_issue_date","emis_prescription_type","emis_registration_organisation_guid","emis_encounter_guid","exa_encounter_guid","end_date","emis_enteredby_userinrole_guid","exa_prescription_guid","estimated_nhs_cost","exa_drug_guid","medication_guid","exa_medication_guid","fhir_medication_intent","exa_mostrecent_issue_date","max_nextissue_days","min_nextissue_days","non_regular_and_current_active_flag","number_authorised","number_of_issues","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","emis_medication_organisation_guid","other_code","other_code_system","prescribed_as_contraceptive_flag","privately_prescribed_flag","quantity","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","reimburse_type","review_date","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","fhir_medication_status","cancellation_date","nhs_prescription_type","uom","uom_dmd"], axis = 1)
medication9 = medication9.set_axis(["nhs_prescribing_agency","emis_drug_guid","authorisedissues_authorised_date","authorisedissues_first_issue_date","cancellation_reason","emis_code_id","confidential_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","dose","emis_medication_status","dummy_patient_flag","duration_in_days","duration_uom","effective_date","effective_date_precision","emis_issue_method","emis_mostrecent_issue_date","emis_prescription_type","emis_registration_organisation_guid","emis_encounter_guid","exa_encounter_guid","end_date","emis_enteredby_userinrole_guid","exa_prescription_guid","estimated_nhs_cost","exa_drug_guid","medication_guid","exa_medication_guid","fhir_medication_intent","exa_mostrecent_issue_date","max_nextissue_days","min_nextissue_days","non_regular_and_current_active_flag","number_authorised","number_of_issues","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","emis_medication_organisation_guid","other_code","other_code_system","prescribed_as_contraceptive_flag","privately_prescribed_flag","quantity","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","reimburse_type","review_date","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","fhir_medication_status","cancellation_date","nhs_prescription_type","uom","uom_dmd"], axis = 1)
medication10 = medication10.set_axis(["nhs_prescribing_agency","emis_drug_guid","authorisedissues_authorised_date","authorisedissues_first_issue_date","cancellation_reason","emis_code_id","confidential_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","dose","emis_medication_status","dummy_patient_flag","duration_in_days","duration_uom","effective_date","effective_date_precision","emis_issue_method","emis_mostrecent_issue_date","emis_prescription_type","emis_registration_organisation_guid","emis_encounter_guid","exa_encounter_guid","end_date","emis_enteredby_userinrole_guid","exa_prescription_guid","estimated_nhs_cost","exa_drug_guid","medication_guid","exa_medication_guid","fhir_medication_intent","exa_mostrecent_issue_date","max_nextissue_days","min_nextissue_days","non_regular_and_current_active_flag","number_authorised","number_of_issues","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","emis_medication_organisation_guid","other_code","other_code_system","prescribed_as_contraceptive_flag","privately_prescribed_flag","quantity","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","reimburse_type","review_date","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","fhir_medication_status","cancellation_date","nhs_prescription_type","uom","uom_dmd"], axis = 1)
medication11 = medication11.set_axis(["nhs_prescribing_agency","emis_drug_guid","authorisedissues_authorised_date","authorisedissues_first_issue_date","cancellation_reason","emis_code_id","confidential_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","dose","emis_medication_status","dummy_patient_flag","duration_in_days","duration_uom","effective_date","effective_date_precision","emis_issue_method","emis_mostrecent_issue_date","emis_prescription_type","emis_registration_organisation_guid","emis_encounter_guid","exa_encounter_guid","end_date","emis_enteredby_userinrole_guid","exa_prescription_guid","estimated_nhs_cost","exa_drug_guid","medication_guid","exa_medication_guid","fhir_medication_intent","exa_mostrecent_issue_date","max_nextissue_days","min_nextissue_days","non_regular_and_current_active_flag","number_authorised","number_of_issues","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","emis_medication_organisation_guid","other_code","other_code_system","prescribed_as_contraceptive_flag","privately_prescribed_flag","quantity","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","reimburse_type","review_date","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","fhir_medication_status","cancellation_date","nhs_prescription_type","uom","uom_dmd"], axis = 1)
medication12 = medication12.set_axis(["nhs_prescribing_agency","emis_drug_guid","authorisedissues_authorised_date","authorisedissues_first_issue_date","cancellation_reason","emis_code_id","confidential_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","dose","emis_medication_status","dummy_patient_flag","duration_in_days","duration_uom","effective_date","effective_date_precision","emis_issue_method","emis_mostrecent_issue_date","emis_prescription_type","emis_registration_organisation_guid","emis_encounter_guid","exa_encounter_guid","end_date","emis_enteredby_userinrole_guid","exa_prescription_guid","estimated_nhs_cost","exa_drug_guid","medication_guid","exa_medication_guid","fhir_medication_intent","exa_mostrecent_issue_date","max_nextissue_days","min_nextissue_days","non_regular_and_current_active_flag","number_authorised","number_of_issues","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","emis_medication_organisation_guid","other_code","other_code_system","prescribed_as_contraceptive_flag","privately_prescribed_flag","quantity","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","reimburse_type","review_date","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","fhir_medication_status","cancellation_date","nhs_prescription_type","uom","uom_dmd"], axis = 1)
medication13 = medication13.set_axis(["nhs_prescribing_agency","emis_drug_guid","authorisedissues_authorised_date","authorisedissues_first_issue_date","cancellation_reason","emis_code_id","confidential_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","dose","emis_medication_status","dummy_patient_flag","duration_in_days","duration_uom","effective_date","effective_date_precision","emis_issue_method","emis_mostrecent_issue_date","emis_prescription_type","emis_registration_organisation_guid","emis_encounter_guid","exa_encounter_guid","end_date","emis_enteredby_userinrole_guid","exa_prescription_guid","estimated_nhs_cost","exa_drug_guid","medication_guid","exa_medication_guid","fhir_medication_intent","exa_mostrecent_issue_date","max_nextissue_days","min_nextissue_days","non_regular_and_current_active_flag","number_authorised","number_of_issues","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","emis_medication_organisation_guid","other_code","other_code_system","prescribed_as_contraceptive_flag","privately_prescribed_flag","quantity","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","reimburse_type","review_date","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","fhir_medication_status","cancellation_date","nhs_prescription_type","uom","uom_dmd"], axis = 1)
medication14 = medication14.set_axis(["nhs_prescribing_agency","emis_drug_guid","authorisedissues_authorised_date","authorisedissues_first_issue_date","cancellation_reason","emis_code_id","confidential_flag","consultation_source_emis_code_id","consultation_source_emis_original_term","dose","emis_medication_status","dummy_patient_flag","duration_in_days","duration_uom","effective_date","effective_date_precision","emis_issue_method","emis_mostrecent_issue_date","emis_prescription_type","emis_registration_organisation_guid","emis_encounter_guid","exa_encounter_guid","end_date","emis_enteredby_userinrole_guid","exa_prescription_guid","estimated_nhs_cost","exa_drug_guid","medication_guid","exa_medication_guid","fhir_medication_intent","exa_mostrecent_issue_date","max_nextissue_days","min_nextissue_days","non_regular_and_current_active_flag","number_authorised","number_of_issues","opt_out_93c1_flag","opt_out_9nd19nu09nu4_flag","opt_out_9nd19nu0_flag","opt_out_9nu0_flag","emis_medication_organisation_guid","other_code","other_code_system","prescribed_as_contraceptive_flag","privately_prescribed_flag","quantity","recorded_date","registration_guid","regular_and_current_active_flag","regular_current_active_and_inactive_flag","regular_patient_flag","reimburse_type","review_date","emis_original_term","sensitive_flag","sensitive_patient_flag","snomed_concept_id","snomed_description_id","fhir_medication_status","cancellation_date","nhs_prescription_type","uom","uom_dmd"], axis = 1)

medication_list = [medication0,medication1,medication2,medication3,medication4,medication5,medication6,medication7,medication8,medication9,medication10,medication11,medication12,medication13,medication14]

medication_table = pd.concat(medication_list)

In [7]:
# Solution 1

psql.sqldf("""
           SELECT SUBSTR(postcode,1,2) AS 'Area',
           COUNT(case when gender = 'Male' then 1 end) AS 'Male',
           COUNT(case when gender = 'Female' then 1 end) AS 'Female',
           COUNT(case when gender = 'Indeterminate' then 1 end) AS 'Indeterminate',
           COUNT(case when gender = 'Unknown' then 1 end) AS 'Unknown',
           COUNT(*) AS 'Total'
           FROM patient
           GROUP BY Area
           ORDER BY Total DESC""")
# psql.sqldf("""
# SELECT gender,COUNT(gender) AS 'Count' FROM patient
# GROUP BY gender """)

    Area  Male  Female  Indeterminate  Unknown  Total
0     LS   873     902            435      430   2640
1     WF   289     281              0        0    570
2     BD   258     265              0        0    523
3     HX   142     131              0        0    273
4     HD   120      97              0        0    217
5   None    57      41              4        3    105
6     S7    30      25              0        0     55
7     OL    15      23              0        0     38
8     BS    11      14              1        0     26
9     SE     8       8              0        0     16
10    N1     5       3              0        0      8
11    WR     4       2              1        0      7
12    TF     4       0              0        0      4
13    SN     3       1              0        0      4
14    HP     1       3              0        0      4
15    W2     0       3              0        0      3
16    SW     1       2              0        0      3
17    S3     1       2              0        0      3
18    EC     1       2              0        0      3
19    CF     3       0              0        0      3
20    W3     1       1              0        0      2
21    SO     2       0              0        0      2
22    NR     0       2              0        0      2
23    NE     1       1              0        0      2
24    AY     1       1              0        0      2
25    YO     1       0              0        0      1
26    XX     1       0              0        0      1
27    W1     0       1              0        0      1
28    UB     0       1              0        0      1
29    SA     1       0              0        0      1
30    S2     0       1              0        0      1
31    S1     1       0              0        0      1
32    OX     1       0              0        0      1
33    OH     1       0              0        0      1
34    NT     0       0              1        0      1
35    NP     1       0              0        0      1
36    NB     1       0              0        0      1
37    N2     0       1              0        0      1
38    MK     0       1              0        0      1
39    M6     1       0              0        0      1
40    LL     0       1              0        0      1
41    LA     0       1              0        0      1
42    G4     0       1              0        0      1
43    G2     0       1              0        0      1
44    EX     0       1              0        0      1
45    EH     0       0              0        1      1
46    E1     0       1              0        0      1
47    DE     0       1              0        0      1
48    BN     0       1              0        0      1
49    BB     1       0              0        0      1
50    BA     0       1              0        0      1
51    B1     0       1              0        0      1
52    AN     1       0              0        0      1

In [108]:
# Non-dummy patients with asthma, with current active flag

psql.sqldf("""
           SELECT DISTINCT(o.registration_guid) FROM observation_table o
           INNER JOIN clinical_codes c ON (o.snomed_concept_id = c.snomed_concept_id)
           WHERE (o.dummy_patient_flag = 'false'
           AND c.refset_simple_id = 999012891000230104
           AND o.regular_and_current_active_flag = 'true')
           """)

                        registration_guid
0    1DBC3EAE-4B99-4240-BBDD-95E99C60463C
1    E26418E2-1C61-4798-A97B-9D88D6CF719D
2    A4373487-FC9F-4842-B94E-E72906BFB10D
3    0ABAB973-882A-418F-8394-45EF598524F6
4    E5BC82BF-B3FD-4562-A982-48F18E3DE6D0
..                                    ...
399  32851B08-43B8-403A-ADFD-9D572CDD12E5
400  45D8B90B-3B70-45FC-B662-3F6260BD483F
401  ABC9990B-BD5A-462D-B3B5-66CEF7017E01
402  A49DAD41-8B00-42F1-8905-05D03F0FE324
403  BFC2AED2-DDBF-4F62-8D2F-5EEA2E8D8701

[404 rows x 1 columns]

In [127]:
psql.sqldf("""
           SELECT p.registration_guid,p.patient_id FROM observation_table o
           JOIN medication_table m ON (p.registration_guid=m.registration_guid)
           JOIN clinical_codes c ON (o.snomed_concept_id = c.snomed_concept_id)
           JOIN patient p ON (o.registration_guid=p.registration_guid)
           GROUP BY p.registration_guid
           HAVING
           COUNT(CASE WHEN c.refset_simple_id = 999012891000230104 AND o.dummy_patient_flag = 'false' AND o.regular_and_current_active_flag = 'true' THEN 1 END)
           AND COUNT(CASE WHEN o.snomed_concept_id = 129490002 OR o.snomed_concept_id = 129490002 OR o.snomed_concept_id = 702408004 OR o.snomed_concept_id = 702801003 OR o.snomed_concept_id = 704459002 THEN 1 END)
           """)
# INNER JOIN medication_table m ON (p.registration_guid=m.registration_guid)

Empty DataFrame
Columns: [registration_guid, patient_id]
Index: []

In [145]:
psql.sqldf("""SELECT * FROM medication_table m 
           """)
# 591221000033116
# 702408004

,nhs_prescribing_agency,emis_drug_guid,authorisedissues_authorised_date,authorisedissues_first_issue_date,cancellation_reason,emis_code_id,confidential_flag,consultation_source_emis_code_id,consultation_source_emis_original_term,dose,...,emis_original_term,sensitive_flag,sensitive_patient_flag,snomed_concept_id,snomed_description_id,fhir_medication_status,cancellation_date,nhs_prescription_type,uom,uom_dmd
0,prescribed-at-gp-practice,None,2005-04-13 00:00:00,2005-04-13 00:00:00,None,266241000033110,false,None,None,APPLY TWICE A DAY,...,Clotrimazole 1% cream,false,false,326203005,107737701000001118,completed,None,acute,gram(s),None
1,prescribed-at-gp-practice,None,2007-08-15 00:00:00,2007-08-15 00:00:00,None,3943341000033113,false,None,None,2 PUFFS BD,...,Clenil Modulite 100micrograms/dose inhaler (Ch...,false,false,10618211000001109,52438301000001111,active,None,repeat,inhaler,None
2,prescribed-at-gp-practice,None,2005-05-10 00:00:00,2005-05-10 00:00:00,None,2215141000033110,false,None,None,5 MLS QDS,...,Paracetamol 250mg/5ml oral suspension sugar free,false,false,39024611000001102,1615391000001112,completed,None,acute,ml,None
3,prescribed-at-gp-practice,None,2008-03-13 00:00:00,2008-03-13 00:00:00,None,849641000033117,false,None,None,5 MLS OD,...,Loratadine 5mg/5ml oral solution,false,false,38896711000001106,1574471000001116,completed,None,acute,ml,None
4,prescribed-at-gp-practice,None,2008-06-14 00:00:00,2008-06-14 00:00:00,None,1467541000033114,false,None,None,10 MLS BD,...,Trimethoprim 50mg/5ml oral suspension sugar free,false,false,39022311000001100,1614851000001112,completed,None,acute,ml,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214011,prescribed-at-gp-practice,23DC3B2A-8984-4EDA-98B9-CFB9D2ECF361,None,None,None,838041000033116,false,None,None,TAKE ONE DAILY,...,Lisinopril Tablets 20 mg,false,false,318860005,56974901000001116,completed,None,repeat,tablet(s),None
214012,prescribed-at-gp-practice,AD382A01-3034-4EC9-9494-285CE5239AF1,None,None,None,1418941000033115,false,None,None,AS DIRECTED,...,Tetanus Immunoglobulin Injection 250 iu/ml p...,false,false,9478811000001102,30981401000001115,completed,None,acute,pre-filled syrg(s),None
214013,prescribed-at-gp-practice,9A4F1F64-F209-40BC-B529-C803E85821C4,None,None,None,91141000033119,false,None,None,OD,...,Atenolol Tablets 50 mg,false,false,318420003,56911901000001114,completed,None,repeat,tablet,None
214014,prescribed-at-gp-practice,97C9D388-B65D-4CD5-9B3F-0BAB037F14D2,None,None,None,1563241000033113,false,None,None,ONE NIGHT,...,Zopiclone Tablets 7.5 mg,false,false,321175006,56913501000001119,completed,None,repeat,tablet(s),None
214015,prescribed-at-gp-practice,234C68C2-00C9-4CF2-A301-7120D39214D1,None,None,None,3196841000033116,false,None,None,AS DIRECTED,...,Fortisip Bottle Liquid Feed (Mixed Flavours) ...,false,false,None,None,completed,None,repeat,bottle(s),None

In [338]:
psql.sqldf("""
           SELECT * FROM clinical_codes c
           WHERE c.refset_simple_id = 999004211000230104
           """)

,refset_simple_id,parent_code_id,code_id,snomed_concept_id,emis_term
0,999004211000230104,None,102921000006112,266918002,Tobacco smoking consumption
1,999004211000230104,None,88471000006112,266920004,Trivial cigarette smoker (less than one cigare...
2,999004211000230104,None,250387019,266918002,Tobacco consumption NOS
3,999004211000230104,None,8153381000006119,428041000124106,Occasional smoker
4,999004211000230104,None,819331000006110,160605003,Heavy cigarette smoker (20-39 cigs/day)
5,999004211000230104,None,5003171000006114,230063004,Heavy cigarette smoker
6,999004211000230104,None,4533531000006119,160613002,Admitted tobacco consumption possibly untrue
7,999004211000230104,None,137791000006118,308438006,Smoking restarted
8,999004211000230104,None,743331000006116,160603005,Light cigarette smoker (1-9 cigs/day)
9,999004211000230104,None,3422221000006116,56771006,Heavy smoker (over 20 per day)
10,999004211000230104,None,5003161000006119,230062009,Moderate cigarette smoker
11,999004211000230104,None,1780360012,401159003,Reason for restarting smoking
12,999004211000230104,None,136515019,82302008,Pipe smoker
13,999004211000230104,None,7375991000006118,449868002,Smokes tobacco daily
14,999004211000230104,None,5003151000006116,230060001,Light cigarette smoker
15,999004211000230104,None,1488577017,394872000,Ready to stop smoking
16,999004211000230104,None,137721000006115,266918002,Smoker - amount smoked
17,999004211000230104,None,5495901000006112,266918002,Amount and type of tobacco smoked
18,999004211000230104,None,4948531000006116,225934006,Smokes in bed
19,999004211000230104,None,250368013,160612007,Keeps trying to stop smoking
20,999004211000230104,None,1592611000000110,446172000,Failed attempt to stop smoking
21,999004211000230104,None,11904991000006116,230059006,Occasional cigarette smoker
22,999004211000230104,None,344793011,230056004,Cigarette consumption
23,999004211000230104,None,8063181000006116,203191000000107,Wants to stop smoking
24,999004211000230104,None,503483019,77176002,Current smoker
25,999004211000230104,None,250372012,160616005,Trying to give up smoking
26,999004211000230104,None,397733018,428041000124106,Occasional smoker
27,999004211000230104,None,1488576014,394871007,Thinking about stopping smoking
28,999004211000230104,None,108938018,65568007,Cigarette smoker
29,999004211000230104,None,344794017,230057008,Cigar consumption
30,999004211000230104,None,3419101000006116,56578002,Moderate smoker (20 or less per day)
31,999004211000230104,None,2670126018,308438006,Smoking restarted
32,999004211000230104,None,2170961000000116,836001000000109,Waterpipe tobacco consumption
33,999004211000230104,None,2474719011,413173009,Minutes from waking to first tobacco consumption
34,999004211000230104,None,12482301000006115,160613002,Admitted tobacco cons untrue ?
35,999004211000230104,None,67621000006112,160606002,Very heavy cigarette smoker (40+ cigs/day)
36,999004211000230104,None,250369017,160613002,Admitted tobacco consumption possibly untrue
37,999004211000230104,None,2669652019,266929003,Smoking started
38,999004211000230104,None,250375014,160619003,Rolls own cigarettes
39,999004211000230104,None,5495951000006111,266920004,Occasional cigarette smoker (less than one cig...
40,999004211000230104,None,5003181000006112,230064005,Very heavy cigarette smoker
41,999004211000230104,None,1488578010,394873005,Not interested in stopping smoking
42,999004211000230104,None,216212011,134406006,Smoking reduced
43,999004211000230104,None,5003141000006118,230059006,Trivial cigarette smoker
44,999004211000230104,None,700121000006118,160604004,Moderate cigarette smoker (10-19 cigs/day)
45,999004211000230104,None,8153371000006117,428041000124106,Occasional tobacco smoker
46,999004211000230104,None,14616531000006112,77176002,Smoking
47,999004211000230104,None,5003191000006110,230065006,Chain smoker
48,999004211000230104,None,99639019,59978006,Cigar smoker
49,999004211000230104,None,5495941000006114,266920004,Occasional smoker
50,999004211000230104,None,344795016,230058003,Pipe tobacco consumption
51,999004211000230104,None,128130017,77176002,Smoker

In [194]:
psql.sqldf("""
           SELECT c.emis_original_term, c.emis_code_id, c.snomed_concept_id, c.snomed_description_id FROM medication_table c
           WHERE c.emis_original_term LIKE '%Olodaterol%'
           LIMIT 100
           """)

Empty DataFrame
Columns: [emis_original_term, emis_code_id, snomed_concept_id, snomed_description_id]
Index: []

In [252]:
# All Prescribed medications checked within last 30 years

psql.sqldf("""
           SELECT m.authorisedissues_authorised_date, m.authorisedissues_first_issue_date,m.effective_date, m.emis_mostrecent_issue_date, m.end_date,m.exa_mostrecent_issue_date, m.recorded_date  FROM medication_table m
           INNER JOIN clinical_codes c ON (m.emis_code_id = c.code_id)
           WHERE c.parent_code_id In (591221000033116,717321000033118,1215621000033114,972021000033115,1223821000033118)
           """)

# AND DATE(m.emis_mostrecent_issue_date) > DATE(CURRENT_DATE,'-30 year')

,authorisedissues_authorised_date,authorisedissues_first_issue_date,effective_date,emis_mostrecent_issue_date,end_date,exa_mostrecent_issue_date,recorded_date
0,None,None,2003-04-02 00:00:00,None,None,None,2003-04-02 00:00:00
1,None,None,2003-05-11 00:00:00,None,None,None,2003-05-11 00:00:00
2,None,None,2003-06-12 00:00:00,None,None,None,2003-06-12 00:00:00
3,None,None,2003-07-19 00:00:00,None,None,None,2003-07-19 00:00:00
4,None,None,2003-08-24 00:00:00,None,None,None,2003-08-24 00:00:00
...,...,...,...,...,...,...,...
2989,None,None,2006-09-06 00:00:00,None,None,None,2006-09-06 00:00:00
2990,None,None,2006-10-04 00:00:00,None,None,None,2006-10-04 00:00:00
2991,None,None,2006-12-09 00:00:00,None,None,None,2006-12-09 00:00:00
2992,2002-10-06 00:00:00,2002-10-06 00:00:00,2002-10-06 00:00:00,2002-12-02 00:00:00,2002-12-30 00:00:00,2002-12-02 00:00:00,2002-10-06 00:00:00
2993,2006-09-06 00:00:00,2006-09-06 00:00:00,2006-09-06 00:00:00,2006-12-09 00:00:00,2006-12-09 00:00:00,2006-12-09 00:00:00,2006-09-06 00:00:00

In [24]:
# Asthma, Smoking, 40kg and COPD

psql.sqldf("""SELECT DISTINCT(observation_table.registration_guid)
           FROM observation_table
           JOIN clinical_codes ON observation_table.emis_code_id = clinical_codes.code_id
           WHERE observation_table.registration_guid NOT IN (
           SELECT DISTINCT(observation_table.registration_guid) FROM observation_table
           JOIN clinical_codes ON observation_table.emis_code_id = clinical_codes.code_id
           WHERE clinical_codes.refset_simple_id IN (999021691000230104,999004211000230104,999011571000230107)
           ) AND clinical_codes.refset_simple_id IN (999012891000230104)
           ORDER BY observation_table.emis_original_term ASC
""")

                       registration_guid
0   09DF981F-24ED-4B8D-86A5-58A6D58A6C24
1   0CBE23E5-5D36-4C7B-9E91-E343F182D463
2   27CC1FCC-43DF-4783-9968-A815D441D338
3   4FA55B96-6588-4EB4-BD14-E868E8FDFCE9
4   5DE3CEFA-A7A1-463C-B328-99EA8F3035F4
..                                   ...
93  C6B03E2C-C8FF-455E-8B54-0AA113555D23
94  1833D75C-6130-41AA-9097-05E6B71035B1
95  8AA27A40-DED4-406F-BEC7-5DEEF5D35FEB
96  A614CDF1-0D8B-4895-943E-013C3EF117F9
97  159518F9-47C5-47F5-9BD2-2EC9878A4C0E

[98 rows x 1 columns]

In [28]:
# Medication and Date

psql.sqldf("""
            SELECT DISTINCT(p.registration_guid) FROM medication_table m
            INNER JOIN clinical_codes c ON (m.emis_code_id = c.code_id)    
            INNER JOIN patient p ON (m.registration_guid = p.registration_guid)
            WHERE (c.parent_code_id IN (591221000033116,717321000033118,1215621000033114,972021000033115,1223821000033118)
            AND DATE(m.recorded_date) > DATE(CURRENT_DATE,'-30 year'))""")

                        registration_guid
0    FE3AD4CE-69AA-4CC9-B16A-566866DFF6DE
1    081295BF-3D65-4969-B542-3AC8749248B4
2    DC132C60-705D-462A-9489-5BCCC0E886C3
3    13EB6EAA-63FA-421B-9C7A-8886ED251556
4    C430DAF9-481E-45AD-ABB6-D7AB0D15B0B0
..                                    ...
129  A19BAC5D-3059-40A8-B954-5CB8031C745F
130  8500FAC6-F2D6-4F6C-8022-BB3AE310532A
131  B020BDC4-3A15-459B-9DC2-83C43F0643FD
132  C0A610F3-0F02-4750-9614-88E09C4F5F2E
133  CE16ECA3-2781-493E-848E-A3C904D69512

[134 rows x 1 columns]

In [48]:
psql.sqldf("""
           
            SELECT DISTINCT(p.registration_guid) 
            FROM medication_table m
            INNER JOIN clinical_codes c ON (m.emis_code_id = c.code_id)    
            INNER JOIN patient p ON (m.registration_guid = p.registration_guid)
            WHERE (c.parent_code_id IN (591221000033116,717321000033118,1215621000033114,972021000033115,1223821000033118)
            AND DATE(m.recorded_date) > DATE(CURRENT_DATE,'-30 year'))
            
            UNION
           
            SELECT DISTINCT(o.registration_guid)
            FROM observation_table o
            INNER JOIN patient p ON (o.registration_guid = p.registration_guid)
            INNER JOIN clinical_codes c ON (o.emis_code_id = c.code_id)
            WHERE o.registration_guid NOT IN (
            SELECT DISTINCT(o.registration_guid) FROM observation_table o
            JOIN clinical_codes c ON o.emis_code_id = c.code_id
            WHERE c.refset_simple_id IN (999021691000230104,999004211000230104,999011571000230107) )
            AND c.refset_simple_id IN (999012891000230104)
           """)

                        registration_guid
0    0281D27E-FDE5-4423-9B4F-03D8E97B3DB8
1    03670D06-84EF-4E11-BD47-01463B066141
2    04E95B60-9540-4DEF-B7BD-0BA1AAC8F74C
3    081295BF-3D65-4969-B542-3AC8749248B4
4    0814EA84-7790-4D22-B174-D66580472CE6
..                                    ...
222  F0DD24A0-D6A5-426E-BD77-B27952C64A6F
223  F1502D05-68D7-4717-97FE-08F43C41637B
224  F45680C4-9740-49FF-9E03-FDAF3A40ED6B
225  F506D2D6-8A8A-4611-8A64-F2B859F67179
226  FE3AD4CE-69AA-4CC9-B16A-566866DFF6DE

[227 rows x 1 columns]

In [59]:
psql.sqldf("""
            SELECT DISTINCT(o.registration_guid)
            FROM observation_table o
            INNER JOIN patient p ON (o.registration_guid = p.registration_guid)
            INNER JOIN clinical_codes c ON (o.emis_code_id = c.code_id)
            WHERE p.registration_guid NOT IN (
            SELECT DISTINCT(o.registration_guid) FROM observation_table o
            JOIN clinical_codes c ON o.emis_code_id = c.code_id
            WHERE c.refset_simple_id IN (999021691000230104,999004211000230104,999011571000230107) 
            AND (o.regular_and_current_active_flag = 'true' OR o.non_regular_and_current_active_flag = 'true'))
            AND c.refset_simple_id IN (999012891000230104) """)

                       registration_guid
0   3D04BEBE-0AAA-4CE2-B710-718BDC1AA1C0
1   788B339F-84BC-46FE-A12A-2D3F5F47AC06
2   CEDE39B9-9261-4B21-9E07-92D4308E87D5
3   A614CDF1-0D8B-4895-943E-013C3EF117F9
4   1833D75C-6130-41AA-9097-05E6B71035B1
..                                   ...
94  EE958FC5-BF45-4865-99DE-5666CEC4D156
95  F03E9998-D4F2-454A-9B8E-3F64F35F9577
96  F0DD24A0-D6A5-426E-BD77-B27952C64A6F
97  F45680C4-9740-49FF-9E03-FDAF3A40ED6B
98  159518F9-47C5-47F5-9BD2-2EC9878A4C0E

[99 rows x 1 columns]

In [78]:
psql.sqldf("""
            SELECT DISTINCT(o.registration_guid),p.patient_id,p.patient_surname,p.patient_givenname,p.postcode,p.age,p.gender
            FROM observation_table o
            INNER JOIN patient p ON (o.registration_guid = p.registration_guid)
            INNER JOIN clinical_codes c ON (o.emis_code_id = c.code_id)
            WHERE p.registration_guid NOT IN (
            SELECT DISTINCT(o.registration_guid) FROM observation_table o
            JOIN clinical_codes c ON o.emis_code_id = c.code_id
            WHERE c.refset_simple_id IN (999021691000230104,999004211000230104,999011571000230107)
            AND (o.regular_and_current_active_flag = 'true' OR o.non_regular_and_current_active_flag = 'true')) 
            AND (c.refset_simple_id IN (999012891000230104)
            AND (o.regular_and_current_active_flag = 'true' OR o.non_regular_and_current_active_flag = 'true'))
            AND (o.opt_out_9nu0_flag = 'false' AND o.opt_out_9nd19nu09nu4_flag = 'false' AND o.dummy_patient_flag ='false')
            AND p.registration_guid IN (
            SELECT DISTINCT(p.registration_guid) 
            FROM medication_table m
            INNER JOIN clinical_codes c ON (m.emis_code_id = c.code_id)    
            INNER JOIN patient p ON (m.registration_guid = p.registration_guid)
            WHERE (c.parent_code_id IN (591221000033116,717321000033118,1215621000033114,972021000033115,1223821000033118)
            AND DATE(m.recorded_date) > DATE(CURRENT_DATE,'-30 year'))
            AND p.date_of_death IS NULL)
           """)

,registration_guid,patient_id,patient_surname,patient_givenname,postcode,age,gender
0,3D04BEBE-0AAA-4CE2-B710-718BDC1AA1C0,11997,Tomlinson,Mark,HD6 1DZ,0,Male
1,E99C8B2D-A129-4711-9815-F276B13D678B,11423,Randall,Susan,BD17 0TZ,0,Female
2,CEDE39B9-9261-4B21-9E07-92D4308E87D5,9972,Law,Frederick,WF13 3RJ,0,Male
3,B7CAB4BE-0731-4ABE-92B4-77CF9384C951,11842,Hewitt,Graham,LS22 3UU,0,Male
4,C6B03E2C-C8FF-455E-8B54-0AA113555D23,10458,Davies,Jane,HX1 1XI,0,Female

In [55]:
psql.sqldf("""SELECT emis_original_term FROM observation_table
           WHERE observation_table.registration_guid = '3D04BEBE-0AAA-4CE2-B710-718BDC1AA1C0'
           LIMIT 55""")

                                   emis_original_term
0         Patient given telephone advice out of hours
1                                Spacer device in use
2                        Asthma management plan given
3                     Asthma clinical management plan
4                           Seen in paediatric clinic
5                                Never smoked tobacco
6                                          Eczema NOS
7         Patient given telephone advice out of hours
8                           Seen in paediatric clinic
9                      Medication review with patient
10                          Notes summary on computer
11                  [V]Examination of eyes and vision
12                   O/E - asymmetrical thigh creases
13                     Medication review with patient
14                                        Viral warts
15                              Seen in asthma clinic
16                                   O/E - itchy rash
17                         Asthma monitoring by nurse
18                     Medication review with patient
19                                           Snuffles
20                          Seen in paediatric clinic
21          Bronchodilators used more than once daily
22                                   Failed encounter
23                                    Chest infection
24               Using inhaled steroids - normal dose
25  Asthma causes daytime symptoms 1 to 2 times pe...
26                       Other hospital admission NOS
27                                   Letter encounter
28                          Seen in paediatric clinic
29                   O/E - asymmetrical thigh creases
30              Upper respiratory tract infection NOS
31              Upper respiratory tract infection NOS
32                                Acute bronchiolitis
33                     Asthma not limiting activities
34                         Did not attend - no reason
35                                         Eczema NOS
36                         Asthma monitoring by nurse
37                     Orthopaedic exam.- general NOS
38                            Asthma disturbing sleep
39                                              Cough
40                       Inhaler technique - moderate
41                          Seen in paediatric clinic
42                                     O/E - dry skin
43                         Asthma monitoring by nurse
44                         Asthma monitoring by nurse
45                         Asthma monitoring by nurse
46                         Asthma monitoring by nurse
47                     Medication review with patient
48                       Acute exacerbation of asthma
49                       Emergency hospital admission
50                          Seen by deputising doctor
51                           Dermatophytosis of scalp
52                       Acute exacerbation of asthma
53                                             Asthma
54                               Undescended testicle

In [ ]:
psql.sqldf("""SELECT * FROM medication_table
           WHERE medication_table.registration_guid = '3D04BEBE-0AAA-4CE2-B710-718BDC1AA1C0'""")

In [220]:
psql.sqldf("""
           SELECT m.emis_mostrecent_issue_date FROM medication_table m
            WHERE m.emis_mostrecent_issue_date > date(CURRENT_DATE()-1)
           """)

      emis_mostrecent_issue_date
0            2005-04-13 00:00:00
1            2007-08-15 00:00:00
2            2005-05-10 00:00:00
3            2008-03-13 00:00:00
4            2008-06-14 00:00:00
...                          ...
58568        2006-06-26 00:00:00
58569        2006-02-14 00:00:00
58570        2006-08-08 00:00:00
58571        2006-01-03 00:00:00
58572        2006-02-18 00:00:00

[58573 rows x 1 columns]

In [245]:
psql.sqldf("""SELECT m.emis_mostrecent_issue_date FROM medication_table m
           WHERE DATE(m.emis_mostrecent_issue_date) > DATE(CURRENT_DATE,'-30 year')""")

      emis_mostrecent_issue_date
0            2005-04-13 00:00:00
1            2007-08-15 00:00:00
2            2005-05-10 00:00:00
3            2008-03-13 00:00:00
4            2008-06-14 00:00:00
...                          ...
58568        2006-06-26 00:00:00
58569        2006-02-14 00:00:00
58570        2006-08-08 00:00:00
58571        2006-01-03 00:00:00
58572        2006-02-18 00:00:00

[58573 rows x 1 columns]

In [246]:
psql.sqldf("""SELECT * FROM medication_table""")

,nhs_prescribing_agency,emis_drug_guid,authorisedissues_authorised_date,authorisedissues_first_issue_date,cancellation_reason,emis_code_id,confidential_flag,consultation_source_emis_code_id,consultation_source_emis_original_term,dose,...,emis_original_term,sensitive_flag,sensitive_patient_flag,snomed_concept_id,snomed_description_id,fhir_medication_status,cancellation_date,nhs_prescription_type,uom,uom_dmd
0,prescribed-at-gp-practice,None,2005-04-13 00:00:00,2005-04-13 00:00:00,None,266241000033110,false,None,None,APPLY TWICE A DAY,...,Clotrimazole 1% cream,false,false,326203005,107737701000001118,completed,None,acute,gram(s),None
1,prescribed-at-gp-practice,None,2007-08-15 00:00:00,2007-08-15 00:00:00,None,3943341000033113,false,None,None,2 PUFFS BD,...,Clenil Modulite 100micrograms/dose inhaler (Ch...,false,false,10618211000001109,52438301000001111,active,None,repeat,inhaler,None
2,prescribed-at-gp-practice,None,2005-05-10 00:00:00,2005-05-10 00:00:00,None,2215141000033110,false,None,None,5 MLS QDS,...,Paracetamol 250mg/5ml oral suspension sugar free,false,false,39024611000001102,1615391000001112,completed,None,acute,ml,None
3,prescribed-at-gp-practice,None,2008-03-13 00:00:00,2008-03-13 00:00:00,None,849641000033117,false,None,None,5 MLS OD,...,Loratadine 5mg/5ml oral solution,false,false,38896711000001106,1574471000001116,completed,None,acute,ml,None
4,prescribed-at-gp-practice,None,2008-06-14 00:00:00,2008-06-14 00:00:00,None,1467541000033114,false,None,None,10 MLS BD,...,Trimethoprim 50mg/5ml oral suspension sugar free,false,false,39022311000001100,1614851000001112,completed,None,acute,ml,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214011,prescribed-at-gp-practice,23DC3B2A-8984-4EDA-98B9-CFB9D2ECF361,None,None,None,838041000033116,false,None,None,TAKE ONE DAILY,...,Lisinopril Tablets 20 mg,false,false,318860005,56974901000001116,completed,None,repeat,tablet(s),None
214012,prescribed-at-gp-practice,AD382A01-3034-4EC9-9494-285CE5239AF1,None,None,None,1418941000033115,false,None,None,AS DIRECTED,...,Tetanus Immunoglobulin Injection 250 iu/ml p...,false,false,9478811000001102,30981401000001115,completed,None,acute,pre-filled syrg(s),None
214013,prescribed-at-gp-practice,9A4F1F64-F209-40BC-B529-C803E85821C4,None,None,None,91141000033119,false,None,None,OD,...,Atenolol Tablets 50 mg,false,false,318420003,56911901000001114,completed,None,repeat,tablet,None
214014,prescribed-at-gp-practice,97C9D388-B65D-4CD5-9B3F-0BAB037F14D2,None,None,None,1563241000033113,false,None,None,ONE NIGHT,...,Zopiclone Tablets 7.5 mg,false,false,321175006,56913501000001119,completed,None,repeat,tablet(s),None
214015,prescribed-at-gp-practice,234C68C2-00C9-4CF2-A301-7120D39214D1,None,None,None,3196841000033116,false,None,None,AS DIRECTED,...,Fortisip Bottle Liquid Feed (Mixed Flavours) ...,false,false,None,None,completed,None,repeat,bottle(s),None

In [111]:
psql.sqldf("""
           SELECT DISTINCT(p.registration_guid) FROM patient p
           WHERE p.date_of_death IS NULL
           """)

                         registration_guid
0     9A70C9CD-D0F7-43F3-A05C-34C8F192E00C
1     57E3019C-25E6-4591-AA6D-3139AF37DC3F
2     A1700F02-134E-42FF-B537-1B7DA00F8C25
3     CEDE39B9-9261-4B21-9E07-92D4308E87D5
4     9532DEBE-42CC-40E4-820A-55DF603E0D23
...                                    ...
4525  61CE65F5-271B-4151-8700-70DE00CC0A9B
4526  4C16CFF4-520C-4B1C-8B03-9B214BDFAC76
4527  21107E5F-CE16-4669-9B6E-43671212E9D0
4528  9F8F0E53-7252-4998-A035-6809941C8A83
4529  F2E5C6F8-52B3-477B-83B2-955A9BB227A5

[4530 rows x 1 columns]

In [75]:
psql.sqldf("""
           SELECT o.regular_and_current_active_flag, o.regular_current_active_and_inactive_flag FROM observation_table o
           WHERE (o.regular_and_current_active_flag = 'false'
           AND o.regular_current_active_and_inactive_flag = 'true')
           """)

    regular_and_current_active_flag regular_current_active_and_inactive_flag
0                             false                                     true
1                             false                                     true
2                             false                                     true
3                             false                                     true
4                             false                                     true
..                              ...                                      ...
259                           false                                     true
260                           false                                     true
261                           false                                     true
262                           false                                     true
263                           false                                     true

[264 rows x 2 columns]

In [62]:
# Solution 2
psql.sqldf("""
           SELECT p.patient_id, p.patient_surname, p.patient_givenname, p.postcode, p.age, p.gender FROM patient p
           JOIN observation_table o ON (p.registration_guid = o.registration_guid)
           JOIN clinical_codes c ON (o.snomed_concept_id = c.snomed_concept_id)
           JOIN medication_table m ON (p.registration_guid = m.registration_guid)""")

           # JOIN clinical_codes c ON (o.snomed_concept_id = c.snomed_concept_id)
           # JOIN medication_table m ON (c.snomed_concept_id = m.snomed_concept_id)

        patient_id patient_surname patient_givenname  postcode age  gender
0            10457            Bibi           Maureen   HX2 8WG   0  Female
1            10457            Bibi           Maureen   HX2 8WG   0  Female
2            10457            Bibi           Maureen   HX2 8WG   0  Female
3            10457            Bibi           Maureen   HX2 8WG   0  Female
4            10457            Bibi           Maureen   HX2 8WG   0  Female
...            ...             ...               ...       ...  ..     ...
7162581      11368       Schofield              Neil  LS28 3VF   0    Male
7162582      11368       Schofield              Neil  LS28 3VF   0    Male
7162583      11368       Schofield              Neil  LS28 3VF   0    Male
7162584      11368       Schofield              Neil  LS28 3VF   0    Male
7162585      11368       Schofield              Neil  LS28 3VF   0    Male

[7162586 rows x 6 columns]